 <style>
                .first {
                    width:50px;
                      border-top:1px solid #136295;
                    border-right:1px solid #136295;
                     border-left:1px solid #136295;
                       border-bottom:1px solid #136295;
                       color:#BDBDBD;
                       font-size: 9px;

                }
                  .second {
                    width:50px;
                      border-top:2px solid black;
                    border-right:1px solid black;
                     border-left:1px solid black;
                       border-bottom:2px solid black;
                       font-size:14px;

                       color:white;
                       background-color:gray;

                }
                .tablegreen td{
					border-collapse: collapse;
					margin:0px;
					border:0.5px solid #136295;
					color:#BDBDBD;
                }

                .tablegreen th{
					border-collapse: collapse;
					margin:0px;
					border:0.5px solid #136295;
					color:#BDBDBD;
                }
                .negrita{
                	color:black;
                }
                 .gris{
                	color:#BDBDBD;
                	font-size: 9px;
                }

                </style>
<table >
	<tr>
		<td valign="baseline" width="120px" style="text-align:left"><img src="/img/firms.documents/logo-bci-vida.jpg" style="width:83px;height:26px;"></td>
		<td valign="baseline" width="230px" style="text-align:center;color:#136295">SOLICITUD DE INCORPORCIÓN Y CERTIFICADO DE COBERTURA
SEGURO DE VIDA DESGRAVAMEN</td>
		<td valign="baseline" width="160px">
			<table>
			<tr>
			<td valign="baseline" width="100%" style="text-align:right"><img src="/img/firms.documents/logo-solventa-creditos.jpg" style="width:83px;height:26px;"></td>
			</tr>
			<tr>
			<td valign="baseline" width="100%" style="text-align:right;color:#136295;font-size:9px;">NRO.PÓLIZA: <?= $datos["nroPoliza2"] ?></td>
			</tr>
			</table>
		</td>

	</tr>
</table>
<table border="1" cellpadding="2" class="tablegreen">
	<tr>
		<td colspan="1" style="text-align:center;"><b>CERTIFICADO DE COBERTURA – VIDA Y DESGRAVAMEN</b></td>
	</tr>
	<tr><td width="50px">FECHA</td><td><?= $datos["fecha"]  ?></td></tr>
	<tr>
		<td colspan="1" width="100%" style="font-weight:900;"><b>IDENTIFICACIÓN DEL ASEGURADO TITULAR</b></td>
	</tr>
	<tr>
		<td colspan="1" width="100%">NOMBRE: <?= $datos["nameClient"]  ?></td>
	</tr>
</table>
<table border="1" cellpadding="2" class="tablegreen">
	<tr>
		<th><b>IDENTIFICACIÓN DEL ASEGURADO TITULAR</b></th>
	</tr>
</table>
<table border="1" cellpadding="2" class="tablegreen">
	<tr>
		<td width="200">FECHA DE NACIMIENTO: <?= $datos["birthDate"] ?> </td>
		<td width="200">RUT:  <?= $datos["nroRut"] ."-". $datos["dgvRut"] ?></td>
<?php if($datos["sexo"]=="MAS"):?>
		<td width="110">SEXO:  F [ ] M [X]  </td>
<?php else: ?>
		<td width="110">SEXO:  F [X] M [ ]  </td>
<?php endif; ?>
	</tr>
</table>

<table border="1" cellpadding="2" class="tablegreen">
	<tr>
		<td width="300">DIRECCIÓN: <?= $datos["calle"] ?> </td>
		<td width="100">Nº: <?= $datos["numCalle"] ?> </td>
		<td width="110">DEPTO/BLOCK:  <?= $datos["numDepto"]."/".$datos["block"] ?> </td>
	</tr>
</table>

<table border="1" cellpadding="2" class="tablegreen">
	<tr>
		<td>CIUDAD: <?= $datos["ciudad"] ?> </td>
		<td>COMUNA: <?= $datos["comuna"] ?> </td>
		<td>TELEFONO: <?= $datos["fonoFijo"] ?> </td>
		<td>CELULAR: <?= $datos["fonoMovil"] ?> </td>
	</tr>
	<tr>
		<TD colspan="4">CORREO ELECTRÓNICO: <?= $datos["email"] ?> </TD>
	</tr>
	<tr>
<?php if($datos["useEmail2"]==1): ?>
		<TD colspan="4" style="text-align:justify">AUTORIZO QUE TODA COMUNICACIÓN Y NOTIFICACIÓN QUE DIGA RELACIÓN CON EL PRESENTE SEGURO ME SEA ENVIADA AL
CORREO ELECTRÓNICO SEÑALADO EN ESTA SOLICITUD DE INCORPORACIÓN. SI (X) NO ( ) </TD>
<?php else: ?>
		<TD colspan="4" style="text-align:justify">AUTORIZO QUE TODA COMUNICACIÓN Y NOTIFICACIÓN QUE DIGA RELACIÓN CON EL PRESENTE SEGURO ME SEA ENVIADA AL
CORREO ELECTRÓNICO SEÑALADO EN ESTA SOLICITUD DE INCORPORACIÓN. SI ( ) NO (X) </TD>
<?php endif; ?>

	</tr>
	<tr>
		<td colspan="4" style="text-align:justify">ANTECEDENTES DE LA COMPAÑÍA ASEGURADORA</td>

	</tr>
	<tr>
			<td colspan="2">BCI SEGUROS VIDA S.A</td>
			<td colspan="2">RUT: 96.573.600-K</td>
	</tr>

	<tr>
		<td colspan="4" style="text-align:justify">ANTECEDENTES DEL CONTRATANTE</td>

	</tr>
	<tr>
			<td colspan="2">SOLVENTA TARJETAS S.A.</td>
			<td colspan="2">RUT: 96.776.000-5</td>
	</tr>

	<tr>
		<td colspan="4" style="text-align:justify">ANTECEDENTES DEL CORREDOR</td>

	</tr>
	<tr>
			<td colspan="2">ARTHUR J. GALLAGHER CORREDORES DE SEGUROS S.A.</td>
			<td colspan="2">RUT: 77.682.370-8</td>
	</tr>

	<tr>
		<td colspan="4" style="text-align:center">DATOS DEL SEGURO</td>

	</tr>
	<tr>
			<td colspan="2">MONTO INICIAL DEL SÚPER AVANCE: <?= $datos["montoLiquido"] ?></td>
			<td colspan="2">NRO. OPERACIÓN: <?= $datos["idDocument"] ?> </td>
	</tr>
	<tr>
			<td colspan="2">FECHA INICIO DEL SÚPER AVANCE: <?= $datos["fechaPrimerVencimiento"] ?></td>
			<td colspan="2">FECHA FIN DEL SÚPER AVANCE: <?= $datos["fechaUltimoVencimiento"] ?> </td>
	</tr>
	<tr>
	<td colspan="4">PRIMA ÚNICA DEL SEGURO: $<?= $datos["costoTotalSeguro2"] ?></td>
	</tr>
	<tr>
		<td colspan="4" style="text-align:center">ASEGURADOS</td>
	</tr>
	<tr>
		<td colspan="4" style="text-align:justify">PERSONAS NATURALES, TARJETAHABIENTES DE TARJETA DE CRÉDITO CRUZ VERDE QUE SOLICITEN UN SÚPER AVANCE, QUE
CUMPLAN LOS REQUISITOS DE ASEGURABILIDAD DETALLADOS EN ESTA COTIZACIÓN.</td>
	</tr>
	<tr>
		<td colspan="4" style="text-align:justify"><span class="negrita">IMPORTANTE:</span> USTED ESTÁ SOLICITANDO SU INCORPORACIÓN COMO ASEGURADO A UNA PÓLIZA O CONTRATO DE SEGURO
COLECTIVO CUYAS CONDICIONES HAN SIDO CONVENIDAS POR SOLVENTA TARJETAS S.A., DIRECTAMENTE CON LA COMPAÑÍA DE
SEGUROS.</td>
	</tr>
</table>
<table  border="1" cellpadding="2" class="tablegreen">
<tr>
	<td style="text-align:center" colspan="1">DETALLE DE COBERTURAS</td>
</tr>
<tr>
	<td style="text-align:center" width="350">COBERTURAS</td>
	<td style="text-align:center">CÓDIGO C.M.F.</td>
</tr>
<tr>
	<td>COBERTURA DE VIDA </td>
	<td>POL 2 2013 1598</td>
</tr>
<tr>
	<td>COBERTURA DE DESGRAVAMEN </td>
	<td>POL 2 2013 0095</td>
</tr>
</table>
<table  border="1" cellpadding="2" class="tablegreen">
	<tr>
		<td style="text-align:center;" colspan="5">DECLARACIÓN PERSONAL DE SALUD PARA ENFERMEDADES GRAVES</td>
	</tr>
	<tr>
		<td style="text-align:center;">NOMBRE</td>
		<td style="text-align:center;">RUT</td>
		<td style="text-align:center;">% BENEFICIO</td>
		<td style="text-align:center;">PARENTESCO</td>
		<td style="text-align:center;">DATOS CONTACTO</td>
	</tr>
	<tr>
		<td style="text-align:center;"><?php echo (isset($datos['nombres1']) ? $datos['nombres1']." ".$datos['apellidoPaterno1']." ".$datos['apellidoMaterno1'] : "" ); ?></td>
		<td style="text-align:center;"><?php echo (isset($datos['rut1']) ? $datos['rut1']."-".$datos['dv1'] : "" ); ?></td>
		<td style="text-align:center;"><?php echo (isset($datos['porcDistribucion1']) ? $datos['porcDistribucion1'] : "" ); ?></td>
		<td style="text-align:center;"><?php echo (isset($datos['parentesco1']) ? $datos['parentesco1'] : "" ); ?></td>
		<td style="text-align:center;"></td>
	</tr>
	<tr>
		<td style="text-align:center;"><?php echo (isset($datos['nombres2']) ? $datos['nombres2']." ".$datos['apellidoPaterno2']." ".$datos['apellidoMaterno2'] : "" ); ?></td>
		<td style="text-align:center;"><?php echo (isset($datos['rut2']) ? $datos['rut2']."-".$datos['dv2'] : "" ); ?></td>
		<td style="text-align:center;"><?php echo (isset($datos['porcDistribucion2']) ? $datos['porcDistribucion2'] : "" ); ?></td>
		<td style="text-align:center;"><?php echo (isset($datos['parentesco2']) ? $datos['parentesco2'] : "" ); ?></td>
		<td style="text-align:center;"></td>
	</tr>
	<tr>
		<td style="text-align:center;"><?php echo (isset($datos['nombres3']) ? $datos['nombres3']." ".$datos['apellidoPaterno3']." ".$datos['apellidoMaterno3'] : "" ); ?></td>
		<td style="text-align:center;"><?php echo (isset($datos['rut3']) ? $datos['rut3']."-".$datos['dv3'] : "" ); ?></td>
		<td style="text-align:center;"><?php echo (isset($datos['porcDistribucion3']) ? $datos['porcDistribucion3'] : "" ); ?></td>
		<td style="text-align:center;"><?php echo (isset($datos['parentesco3']) ? $datos['parentesco3'] : "" ); ?></td>
		<td style="text-align:center;"></td>
	</tr>
	<tr>
		<td style="text-align:center;"><?php echo (isset($datos['nombres3']) ? $datos['nombres4']." ".$datos['apellidoPaterno4']." ".$datos['apellidoMaterno4'] : "" ); ?></td>
		<td style="text-align:center;"><?php echo (isset($datos['rut4']) ? $datos['rut4']."-".$datos['dv4'] : "" ); ?></td>
		<td style="text-align:center;"><?php echo (isset($datos['porcDistribucion4']) ? $datos['porcDistribucion4'] : "" ); ?></td>
		<td style="text-align:center;"><?php echo (isset($datos['parentesco4']) ? $datos['parentesco4'] : "" ); ?></td>
		<td style="text-align:center;"></td>
	</tr>
</table>

<br>
<div class="first">SOLICITUD DE INCORPORACIÓN, MANDATO Y AUTORIZACIÓN DE CARGO EN SÚPER AVANCE.</div>
<span class="gris" style="text-align:justify;font-size:8px;">MEDIANTE LA PRESENTE SOLICITUD DE INCORPORACIÓN Y CERTIFICADO DE COBERTURA SOLICITO SER INCORPORADO A ESTA
PÓLIZA COLECTIVA CUYOS TÉRMINOS, NATURALEZA, CONDICIONES DE ASEGURABILIDAD, COBERTURA, VIGENCIA, EXCLUSIONES,
COMISIONES Y DEMÁS CARACTERÍSTICAS DECLARO CONOCER A CABALIDAD POR HABERME SIDO EXPLICADAS Y POR HABER TENIDO
A LA VISTA, PREVIO A MI FIRMA, EL CERTIFICADO DE COBERTURA Y, LAS CONDICIONES PARTICULARES Y GENERALES QUE SE
DETALLAN SUFICIENTEMENTE. DECLARO ADEMÁS, QUE CONTRATO VOLUNTARIO E INFORMADAMENTE ESTE SEGURO. ASIMISMO
OTORGO MANDATO Y FACULTO A SOLVENTA TARJETAS S.A. PARA INCORPORARME EN CALIDAD DE ASEGURADO, A LA PÓLIZA
COLECTIVA: <?= $datos["nroPoliza2"] ?> Y AGREGAR EL VALOR DE LA PRIMA ÚNICA, AL MONTO DEL SÚPER AVANCE QUE ME HA SIDO OTORGADO POR
SOLVENTA TARJETAS S.A. EL MANDATARIO RENDIRÁ CUENTA DE SU MANDATO ENTREGÁNDOLE AL ASEGURADO AL MOMENTO DE
CONTRATAR EL SÚPER AVANCE UNA LIQUIDACIÓN DEL SÚPER AVANCE, EN DONDE SE INDIQUE EL CARGO DE LA PRIMA
CORRESPONDIENTE. EL CLIENTE ASEGURABLE AUTORIZA A SOLVENTA TARJETAS S.A. Y A LA COMPAÑÍA ASEGURADORA, PARA
QUE LOS DATOS SUMINISTRADOS SEAN UTILIZADOS PARA LA ADMINISTRACIÓN Y AUDITORÍA DEL SEGURO CONTRATADO, EL
OFRECIMIENTO DE OTROS SEGUROS U OTROS SÚPER AVANCES EN LOS QUE PUDIERE ESTAR INTERESADO.
MEDIANTE LA SIGUIENTE FIRMA, ACEPTO LA CONTRATACIÓN DE ESTE SEGURO.
</span>
<div style="text-align:center"><img src="/img/firms.documents/firm1-seguros.png" style="width:687px;height:144px;"></div>
<br>
<div class="first" style="text-align: center">
	DESCRIPCIÓN DE COBERTURAS Y CONDICIONES DE ASEGURABILIDAD
</div>
<br>
<span class="negrita">MATERIA Y MONTO ASEGURADO</span>

<br>
<span class="gris" style="text-align: justify"><span class="negrita">VIDA</span><BR>LA COMPAÑÍA ASEGURADORA PAGARÁ AL (LOS) BENEFICIARIO(S) DESIGNADOS POR EL ASEGURADO, EL CAPITAL ASEGURADO, UNA
VEZ ACREDITADO EL FALLECIMIENTO DEL ASEGURADO DURANTE LA VIGENCIA DEL SÚPER AVANCE Y SIEMPRE QUE SE CUMPLAN
TODAS LAS CONDICIONES ESTIPULADAS EN LAS CONDICIONES PARTICULARES. EL CAPITAL ASEGURADO SERÁ IGUAL AL 80% DEL
MONTO INICIAL DEL SÚPER AVANCE. PARA ESTOS EFECTOS, SE ENTENDERÁ MONTO INICIAL DEL SÚPER AVANCE AL MONTO LÍQUIDO
ENTREGADO AL CLIENTE POR CONCEPTO DEL SÚPER AVANCE CONTRATADO A SOLVENTA TARJETAS S.A.
</span>
<br>
<span class="gris" style="text-align: justify"><span class="negrita">DESGRAVAMEN</span><BR>CUBRE EL SALDO INSOLUTO DE LA DEUDA DEL SÚPER AVANCE CONTRATADO POR EL SEGURADO CON SOLVENTA TARJETAS
S.A.,ANTE EL FALLECIMIENTO DEL ASEGURADO, DURANTE TODA LA VIGENCIA DEL SÚPER AVANCE. LA COMPAÑÍA ASEGURADORA
PAGARÁ AL BENEFICIARIO SOLVENTA TARJERAS S.A., EL CAPITAL ASEGURADO UNA VEZ ACREDITADO EL FALLECIMIENTO DEL
ASEGURADO Y SIEMPRE QUE SE CUMPLAN TODAS LAS CONDICIONES ESTIPULADAS EN LAS CONDICIONES PARTICULARES. EL
CAPITAL ASEGURADO CORRESPONDE PARA EFECTOS DE LA COBERTURA DE DESGRAVAMEN, CORRESPONDE AL SALDO INSOLUTO
DEL SÚPER AVANCE, VIGENTE A LA FECHA DE OCURRENCIA DEL SINIESTRO, SOBRE LA BASE DE UN SERVICIO REGULAR DE LA
DEUDA. QUEDA EXCLUIDO LO ADEUDADO POR MORA O SIMPLE RETARDO.
EN CASO DE REFINANCIAMIENTO O RENEGOCIACIONES DEL SÚPER AVANCE IMPLICAN EL TÉRMINO DE LA PÓLIZA VIGENTE Y PARA
QUE EL ASEGURADO CONTINÚE CON COBERTURA, SERÁ NECESARIO LA CONTRATACIÓN VOLUNTARIA DE UNA NUEVA PÓLIZA.
SE ESTABLECE UN TOPE DE INDEMNIZACIÓN IGUAL A UF 180, POR ASEGURADO, EN EL CASO DE SÚPER AVANCE.
</span>
<br>
<span class="gris" style="text-align: justify"><span class="negrita">INTERÉS ASEGURABLE</span><BR>EL INTERÉS ASEGURABLE POR PARTE DEL ASEGURADO CORRESPONDE A SU PROPIA VIDA.
</span>
<br>
<span class="gris" style="text-align: justify"><span class="negrita">REQUISITOS DE ASEGURABILIDAD</span><br></span>
<table border="1" cellpadding="2" class="tablegreen">
		<tr>
			<td>EDAD MÍNIMA DE INGRESO: 18 <br>AÑOS.</td>
			<td>EDAD MÁXIMA DE INGRESO: 74 AÑOS Y 364 <br>DÍAS</td>
			<td>EDAD MÁXIMA DE COBERTURA: 79 AÑOS Y 364 <br>DÍAS.</td>
		</tr>
</table>
<br>
<span class="gris" style="text-align: justify">LA EDAD DE INGRESO DEL ASEGURADO MÁS EL PLAZO DEL SÚPER AVANCE NO DEBEN SUPERAR LA EDAD MÁXIMA DE COBERTURA.
EL PLAZO DE COBERTURA DEL SEGURO DE VIDA Y DESGRAVAMEN ES TODA LA VIGENCIA DEL SÚPER AVANCE OTORGADO AL
ASEGURADO. DADA LA NATURALEZA DE ESTE SEGURO COLECTIVO, SOLO SE PODRÁ CONTRATAR EN FORMA VOLUNTARIA Y
SIMULTÁNEA AL CURSE DEL SÚPER AVANCE, NO PUDIENDO SER CONTRATADA CON ANTERIORIDAD O DURANTE LA VIGENCIA DEL
MISMO.
</span>
<br>
<span class="gris" style="text-align: justify"><span class="negrita">BENEFICIARIOS</span><br>MIENTRAS EL SÚPER AVANCE SE ENCUENTRE VIGENTE, EL BENEFICIARIO SERÁ SOLVENTA TARJETAS S.A., EN SU CALIDAD DE
CONTRATANTE Y ACREEDOR DEL SÚPER AVANCE, POR EL MONTO CORRESPONDIENTE AL SALDO INSOLUTO DE LA DEUDA AL
MOMENTO DE FALLECIMIENTO DEL ASEGURADO. EL MONTO CORRESPONDIENTE A LA COBERTURA DE VIDA, SERÁ ENTREGADO
DIRECTAMENTE A LOS BENEFICIARIOS DESIGNADOS POR EL ASEGURADO O A FALTA DE DESIGNACIÓN, A SUS HEREDEROS LEGALES.
EN CASO QUE AL MOMENTO DE FALLECIMIENTO DEL ASEGURADO, EL SÚPER AVANCE SE ENCONTRARE PAGADO, POR CUALQUIER
MOTIVO, EL BENEFICIARIO SERÁ EL DESIGNADO POR EL PROPIO ASEGURADO AL MOMENTO DE LA CONTRATACIÓN DEL SEGURO O SUS
HEREDEROS LEGALES EN CASO QUE NO EXISTA DESIGNACIÓN EXPRESA. LA INDEMNIZACIÓN CORRESPONDERÁ AL 80% DEL MONTO
INICIAL DEL SÚPER AVANCE</span>
<br>
<span class="gris" style="text-align: justify"><span class="negrita">COBERTURA DE VIDA (POL 2 2013 1598, ARTÍCULO N°2)</span><br>EL CAPITAL ASEGURADO DE LA PÓLIZA SERÁ PAGADO POR BCI SEGUROS VIDA S.A., A LOS BENEFICIARIOS, UNA VEZ OCURRIDO EL
FALLECIMIENTO DEL ASEGURADO, SI ÉSTE OCURRE DURANTE LA VIGENCIA DE ESTA PÓLIZA Y POR CAUSA NO EXCLUIDA EN ESTE
CONTRATO DE SEGURO. SI EL ASEGURADO SOBREVIVE A LA FECHA DE VENCIMIENTO DEL CONTRATO DE SEGURO, NO TENDRÁ
DERECHO A INDEMNIZACIÓN ALGUNA.</span>
<br>
<span class="gris" style="text-align: justify"><span class="negrita">COBERTURA DE DESGRAVAMEN (POL 2 2013 0095, ARTÍCULO N°2)</span><br>BCI SEGUROS VIDA S.A., ASEGURA LA VIDA DE LOS DEUDORES DEL CONTRATANTE., QUE SE HAYAN INCORPORADO A LA PÓLIZA. DE
ACUERDO A LO ANTERIOR, LA INDEMNIZACIÓN CORRESPONDIENTE AL CAPITAL ASEGURADO DE UN DEUDOR-ASEGURADO, SERÁ
PAGADO POR LA BCI SEGUROS VIDA S.A., AL ACREEDOR BENEFICIARIO, INMEDIATAMENTE DESPUÉS DEHABERSE COMPROBADO POR
ÉSTA QUE EL FALLECIMIENTO DEL ASEGURADO OCURRIÓ DURANTE LA VIGENCIA DE LA COBERTURA PARA DICHO ASEGURADO, Y
QUE NO SE PRODUJO BAJO ALGUNAS DE LAS EXCLUSIONES SEÑALADAS EN ESTA PÓLIZA. SI EL ASEGURADO SOBREVIVE A LA
FECHA DE VENCIMIENTO DE LA COBERTURA OTORGADA POR ESTA PÓLIZA, NO HABRÁ DERECHO A INDEMNIZACIÓN ALGUNA.</span>
<br>
<span class="negrita">PLAZO DE COBERTURA</span><br>

<table border="1" cellpadding="2" class="tablegreen">
		<tr>
			<td>DESGRAVAMEN: EL PLAZO DEL SÚPER AVANCE</td>
			<td>FALLECIMIENTO: EL PLAZO DEL SÚPER AVANCE</td>
		</tr>
</table>

<span class="gris" style="text-align: justify"><span class="negrita">PRIMA DEL SEGURO</span><BR>LA PRIMA SE CALCULARÁ MULTIPLICANDO LA TASA ÚNICA DE CADA SEGURO POR EL MONTO INICIAL DEL SÚPER AVANCE, MÁS
GASTOS NOTARIALES Y SEGUROS VOLUNTARIOS. ESTO ES:</span>
<br>

<table border="1" cellpadding="2" class="tablegreen">
	<tr>
			<td><span class="negrita">SEGURO</span></td>
			<td><span class="negrita">TASA NETA ÚNICA</span></td>
			<td><span class="negrita">TASA BRUTA ÚNICA</span></td>
	</tr>
	<tr>
			<td>VIDA</td>
			<td>9%</td>
			<td>9%</td>
	</tr>
	<tr>
			<td>DESGRAVAMEN</td>
			<td>1%</td>
			<td>1%</td>
	</tr>
	<tr>
			<td>TOTAL</td>
			<td>10%</td>
			<td>10%</td>
	</tr>

</table>
<BR>
<span class="gris" style="text-align: justify">SE CONSIDERA UNA PRIMA TOPE IGUAL A $238.000.</span>
<br>
<br>
<br>
<div class="first" style="text-align: center">EXCLUSIONES</div>
<br>
<br>
<span class="gris" style="text-align: justify"><span class="negrita">EXCLUSIONES COBERTURA DE VIDA (POL 2 2013 1598, ARTÍCULO N°3)</span><BR>ESTE SEGURO NO CUBRE EL FALLECIMIENTO DEL ASEGURADO CUANDO ÉSTA SE PRODUCE A CONSECUENCIA DE, O POR
COMPLICACIONES DE: A) SUICIDIO O MUERTE PRODUCIDA A CONSECUENCIA DE LESIONES AUTO INFERIDAS. NO OBSTANTE RESPECTO</span>
<br>
<br>
<br>
<br>
<br>
<span class="gris" style="text-align: justify">DE LA COBERTURA QUE OTORGA ESTA PÓLIZA, LA ASEGURADORA PAGARÁ EL CAPITAL ASEGURADO A LOS BENEFICIARIOS, SI EL
FALLECIMIENTO OCURRIERA COMO CONSECUENCIA DE SUICIDIO, SIEMPRE QUE HUBIERA TRANSCURRIDO UN (1) AÑO COMPLETO E
ININTERRUMPIDO DESDE LA FECHA DE INCORPORACIÓN DEL ASEGURADO O DESDE EL AUMENTO DE CAPITAL ASEGURADO. EN ESTE
ÚLTIMO CASO EL PLAZO SE CONSIDERARÁ SÓLO PARA EL PAGO DEL INCREMENTO DEL CAPITAL ASEGURADO.<br>
B) PENA DE MUERTE O POR PARTICIPACIÓN DEL ASEGURADO EN CUALQUIER ACTO DELICTIVO, EN CALIDAD DE AUTOR, CÓMPLICE O
ENCUBRIDOR.<br>
C) NEGLIGENCIA, IMPRUDENCIA O CULPA GRAVE POR PARTE DEL ASEGURADO, INCLUYÉNDOSE LA MUERTE DEL ASEGURADO A
CAUSA O CON OCASIÓN DE SU ESTADO DE EBRIEDAD, O ACTO DELICTIVO CALIFICADOS COMO DELITO POR LA LEY, COMETIDO EN
CALIDAD DE AUTOR O CÓMPLICE, POR UN BENEFICIARIO O QUIEN PUDIERA RECLAMAR EL CAPITAL ASEGURADO. EN EL EVENTO DE
EXISTIR MÁS DE UN BENEFICIARIO, LA ASEGURADORA PAGARÁ A LOS RESTANTES BENEFICIARIOS, NO COMPRENDIDOS EN ESTA
CAUSAL<br>
D) GUERRA, INVASIÓN, ACTOS DE ENEMIGOS EXTRANJEROS, HOSTILIDADES U OPERACIONES BÉLICAS, SEA QUE HAYA HABIDO O NO
DECLARACIÓN DE GUERRA, GUERRA CIVIL, INSURRECCIÓN, SUBLEVACIÓN, REBELIÓN, SEDICIÓN, MOTÍN O HECHOS QUE LAS LEYES
CALIFICAN COMO DELITOS CONTRA LA SEGURIDAD INTERIOR DEL ESTADO, YA SEA, CON PARTICIPACIÓN DIRECTA O NO DEL
ASEGURADO EN ESTOS ACTOS.<br>
F) POR PARTICIPACIÓN ACTIVA DEL ASEGURADO EN ACTO TERRORISTA. ENTENDIÉNDOSE POR ACTO TERRORISTA TODA CONDUCTA
CALIFICADA COMO TAL POR LA LEY, ASÍ COMO EL USO DE FUERZA O VIOLENCIA O LA AMENAZA DE ÉSTA, POR PARTE DE
CUALQUIER PERSONA O GRUPO, MOTIVADO POR CAUSAS POLÍTICAS, RELIGIOSAS, IDEOLÓGICAS O SIMILARES, CON LA INTENCIÓN DE
EJERCER INFLUENCIA SOBRE CUALQUIER GOBIERNO O DE ATEMORIZAR A LA POBLACIÓN, O A CUALQUIER SEGMENTO DE LA MISMA.<br>
G) FISIÓN O FUSIÓN NUCLEAR O CONTAMINACIÓN RADIOACTIVA.</span>
<br>
<span class="gris" style="text-align: justify"><span class="negrita">EXCLUSIONES COBERTURA DE DESGRAVAMEN (POL 2 2013 0095, ARTÍCULO N°3)</span><BR>ESTE SEGURO NO CUBRE EL RIESGO DE MUERTE SI EL FALLECIMIENTO DEL ASEGURADO FUERE CAUSADO POR:<br>
A) SUICIDIO, AUTOMUTILACIÓN, O AUTOLESIÓN, A MENOS QUE DE ACUERDO AL N°8 DEL ARTÍCULO 524 DEL CÓDIGO DE COMERCIO SE
ACREDITE QUE EL ASEGURADO ACTUÓ TOTALMENTE PRIVADO DE LA RAZÓN, CORRESPONDIENDO, EN TODO CASO, A LA COMPAÑÍA
ASEGURADORA ACREDITAR EL HECHO DEL SUICIDIO. NO OBSTANTE, LA COMPAÑÍA ASEGURADORA PAGARÁ EL CAPITAL
ASEGURADO AL BENEFICIARIO, SI EL FALLECIMIENTO OCURRIERA COMO CONSECUENCIA DE SUICIDIO, SIEMPRE QUE HUBIERA
TRANSCURRIDO EL PLAZO SEÑALADO EN LAS CONDICIONES PARTICULARES DE LA PÓLIZA, EL QUE A FALTA DE ESTIPULACIÓN EN
ELLAS, SERÁ DE UN (1) AÑO COMPLETO E ININTERRUMPIDO, CONTADO DESDE LA FECHA DE INICIO DE VIGENCIA DE LA COBERTURA
DEL ASEGURADO INDICADO EN LAS CONDICIONES PARTICULARES DE LA PÓLIZA, DESDE SU REHABILITACIÓN, EN SU CASO, O DESDE
EL AUMENTO DE CAPITAL ASEGURADO. EN ÉSTE ÚLTIMO CASO, EL PLAZO SE CONSIDERARÁ SÓLO PARA EL PAGO DE LA
INDEMNIZACIÓN CORRESPONDIENTE AL INCREMENTO DEL CAPITAL ASEGURADO.
B) PENA DE MUERTE O POR PARTICIPACIÓN DEL ASEGURADO EN CUALQUIER ACTO DELICTIVO.<br>
C) POR QUIEN PUDIERE VERSE BENEFICIADO POR EL PAGO DE LA CANTIDAD ASEGURADA, MEDIANTE SU PARTICIPACIÓN COMO
AUTOR O CÓMPLICE EN UN ACTO QUE SEA CALIFICADO POR LA LEY COMO DELITO.<br>
D) LA PARTICIPACIÓN ACTIVA DEL ASEGURADO EN GUERRA INTERNACIONAL, SEA QUE CHILE TENGA O NO INTERVENCIÓN EN ELLA;
EN GUERRA CIVIL, DENTRO O FUERA DE CHILE; O EN MOTÍN O CONMOCIÓN CONTRA EL ORDEN PÚBLICO DENTRO O FUERA DEL PAÍS; O
HECHOS QUE LAS LEYES CALIFICAN COMO DELITOS CONTRA LA SEGURIDAD INTERIOR DEL ESTADO.<br>
E) LA PARTICIPACIÓN ACTIVA DEL ASEGURADO EN ACTO TERRORISTA, ENTENDIÉNDOSE POR ACTO TERRORISTA TODA CONDUCTA
CALIFICADA COMO TAL POR LA LEY, ASÍ COMO EL USO DE FUERZA O VIOLENCIA O LA AMENAZA DE ÉSTA, POR PARTE DE
CUALQUIER PERSONA O GRUPO, MOTIVADO POR CAUSAS POLÍTICAS, RELIGIOSAS, IDEOLÓGICAS O SIMILARES, CON LA INTENCIÓN DE
EJERCER INFLUENCIA SOBRE CUALQUIER GOBIERNO O DE ATEMORIZAR A LA POBLACIÓN, O A CUALQUIER SEGMENTO DE LA MISMA.<br>
F) LA PARTICIPACIÓN DEL ASEGURADO EN ACTOS TEMERARIOS O EN CUALQUIER MANIOBRA, EXPERIMENTO, EXHIBICIÓN, DESAFÍO O
ACTIVIDAD NOTORIAMENTE PELIGROSA, ENTENDIENDO POR TALES AQUELLAS EN LAS CUALES SE PONE EN GRAVE PELIGRO LA
VIDA E INTEGRIDAD FÍSICA DE LAS PERSONAS.<br>
I) FISIÓN O FUSIÓN NUCLEAR O CONTAMINACIÓN RADIOACTIVA.<br>
J) UNA INFECCIÓN OPORTUNÍSTICA, O UN NEOPLASMA MALIGNO, SI AL MOMENTO DE LA MUERTE O ENFERMEDAD EL ASEGURADO
SUFRÍA DEL SÍNDROME DE INMUNODEFICIENCIA ADQUIRIDA. CON TAL PROPÓSITO, SE ENTENDERÁ POR: "SÍNDROME DE
INMUNODEFICIENCIA ADQUIRIDA", LO DEFINIDO PARA TAL EFECTO POR LA ORGANIZACIÓN MUNDIAL DE LA SALUD. INFECCIÓN
OPORTUNÍSTICA INCLUYE, PERO NO DEBE LIMITARSE A NEUMONÍA CAUSADA POR PNEUMOCYSTIS CARINII, ORGANISMO DE ENTERITIS
CRÓNICA, INFECCIÓN VÍRICA O INFECCIÓN MICROBACTERIANA DISEMINADA. NEOPLASMA MALIGNO INCLUYE, PERO NO DEBE
LIMITARSE AL SARCOMA DE KAPOSI, AL LINFOMA DEL SISTEMA NERVIOSO CENTRAL O A OTRAS AFECCIONES MALIGNAS YA
CONOCIDAS O QUE PUEDAN CONOCERSE COMO CAUSAS INMEDIATAS DE MUERTE EN PRESENCIA DE UNA INMUNODEFICIENCIA
ADQUIRIDA. SÍNDROME DE INMUNODEFICIENCIA ADQUIRIDA DEBE INCLUIR ENCEFALOPATÍA (DEMENCIA) DE V.I.H. (VIRUS DE
INMUNODEFICIENCIA HUMANO) Y SÍNDROME DE DESGASTE POR V.I.H. (VIRUS DE INMUNODEFICIENCIA HUMANO). DE OCURRIR EL
FALLECIMIENTO DEL ASEGURADO DEBIDO A ALGUNO DE LOS HECHOS O CIRCUNSTANCIAS ANTES SEÑALADAS, SE ENTENDERÁ QUE
NO EXISTE COBERTURA PARA EL CASO EN PARTICULAR, Y PRODUCIRÁ EL TÉRMINO DEL SEGURO PARA DICHO ASEGURADO, NO
EXISTIENDO OBLIGACIÓN DE INDEMNIZACIÓN ALGUNA POR PARTE DE LA COMPAÑÍA ASEGURADORA. CONFORME A LO ANTERIOR, Y
POR SU NATURALEZA, LA PÓLIZA SEGUIRÁ VIGENTE PARA TODOS LOS EFECTOS CON RESPECTO A LOS DEMÁS ASEGURADOS.</span>
<br>
<div class="first" style="text-align: center;">PROCEDIMIENTO DE DENUNCIA DE SINIESTRO</div>
<br>
<span class="gris" style="text-align: justify">EN CASO DE CONSULTAS, RECLAMOS Y DENUNCIAS DE SINIESTRO, EL ASEGURADO SE DEBERÁ COMUNICAR AL TELÉFONO DEL
CENTRO DE RESPUESTA INMEDIATA (CRI) DE LA COMPAÑÍA DE SEGUROS 600 6000 292 - DESDE CELULAR 2 2679 9700 O EN
CUALQUIERA DE LAS OFICINAS DE BCI SEGUROS VIDA S.A.<br>
EN TODOS LOS CASOS LA COMPAÑÍA SE RESERVA EL DERECHO DE PEDIR MAYORES ANTECEDENTES PARA LA LIQUIDACIÓN DEL
SINIESTRO. EN TODAS LAS DENUNCIAS DEBERÁ DEJARSE CONSTANCIA DEL NOMBRE, DIRECCIÓN Y TELÉFONO DE LA PERSONA
DENUNCIANTE PARA POSTERIORES CONTACTOS QUE SEAN NECESARIOS.
</span>
<BR>
<span class="gris" style="text-align: justify"><span class="negrita">DOCUMENTOS A PRESENTAR</span><BR>PRODUCIDO EL FALLECIMIENTO DEL ASEGURADO, EL BENEFICIARIO DEBERÁ COMUNICARLO POR ESCRITO A LA COMPAÑÍA DENTRO
DE UN PLAZO DE NOVENTA (90) DIÁS CORRIDOS. EL CUMPLIMIENTO EXTEMPORÁNEO DE ESTA OBLIGACIÓN HARÁ PERDER EL
DERECHO A LA INDEMNIZACIÓN ESTABLECIDA EN LA PRESENTE, SALVO EN CASO DE FUERZA MAYOR.<BR>
EN CASO DE FALLECIMIENTO, LOS BENEFICIARIOS DEBERÁN PRESENTAR A LA COMPAÑÍA LA SIGUIENTE DOCUMENTACIÓN:</span>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<span class="gris" style="text-align: justify">
	<ul>
		<li>FORMULARIO DE DENUNCIA DE SINIESTROS COMPLETO.</li>
		<li>FOTOCOPIA DE LA CÉDULA DE IDENTIDAD DEL ASEGURADO FALLECIDO</li>
		<li>CERTIFICADO DE DEFUNCIÓN ORIGINAL, CON LA CAUSA DE MUERTE.</li>
		<li>EN CASO DE MUERTE PRESUNTA, ÉSTA DEBERÁ ACREDITARSE DE CONFORMIDAD A LA LEY</li>
		<li>EN CASO DE MUERTE ACCIDENTAL SE DEBERÁ PRESENTAR PARTE POLICIAL, ALCOHOLEMIA, AUTOPSIA O DICTAMEN DE LA
JUSTICIA.</li>
<li>ECERTIFICADO DE PRUEBA DE MUERTE.</li>
<li>SOLICITUD DE INCORPORACIÓN AL SEGURO DEBIDAMENTE FIRMADO POR EL ASEGURADO</li>
<li>TABLA DE DESARROLLO DEL SÚPER AVANCE QUE DEBE INDICAR EL ESTADO DEL SERVICIO DE LA DEUDA EMITIDO POR LA
ENTIDAD CONTRATANTE A LA FECHA DE FALLECIMIENTO.</li>
<li>OTROS ANTECEDENTES QUE SE ESTIMEN CONVENIENTES Y NECESARIOS PARA LA EVALUACIÓN DEL SINIESTRO.</li>
	</ul>
	<br>
	<br>
	EN CASO DE NO EXISTIR BENEFICIARIOS DESIGNADOS SE DEBERÁ PRESENTAR:
	<br>
	<ul>
		<li>POSESIÓN EFECTIVA LEGALIZADA ANTE NOTARIO.</li>
		<li>CÉDULAS DE IDENTIDAD DE LOS HEREDEROS (POR AMBOS LADOS)</li>
		<li>PODER NOTARIAL DONDE LA SUCESIÓN NOMBRE UN REPRESENTANTE DE LA MISMA, PARA EFECTOS DE PAGO DE LA
INDEMNIZACIÓN.</li>
	</ul>
</span>

<br>
<div class="first" style="text-align: center;">NOTAS IMPORTANTES</div>
<br>

<span class="gris" style="text-align: justify">
	1- EL ASEGURADO DECLARA ESTAR EN CONOCIMIENTO DE; A) EL ASEGURADO DECLARA CONOCER, HABER SIDO PREVIA Y
COMPLETAMENTE INFORMADO Y ACEPTAR LAS CONDICIONES SEÑALADAS EN ESTA SOLICITUD DE INCORPORACIÓN Y CERTIFICADO
DE COBERTURA QUE SUSCRIBE EN MANIFESTACIÓN DE SU VOLUNTAD DE CONTRATAR EL SEGURO. B) EL ASEGURADO HA TOMADO
CONOCIMIENTO DEL DERECHO A DECIDIR SOBRE LA CONTRATACIÓN VOLUNTARIA DEL SEGURO Y LA LIBRE ELECCIÓN DE LA
COMPAÑÍA ASEGURADORA. C) EL CONTRATANTE COLECTIVO DE LA PÓLIZA N° <?= $datos["nroPoliza2"] ?> SERÁ SOLVENTA TARJETAS S.A. D) LAS
COBERTURAS TENDRÁN VIGENCIA DESDE LA FIRMA DEL ASEGURADO. EN ESTE CASO LA PRESENTE SOLICITUD HARÁ LAS VECES DE
CERTIFICADO DE COBERTURA CONFORME A LA CIRCULAR N° 2123 DE LA COMISIÓN PARA EL MERCADO FINANCIERO.
<br>
2- LA PRESENTE SOLICITUD DE INCORPORACIÓN Y CERTIFICADO DE COBERTURA ES UN RESUMEN CON LA DESCRIPCIÓN GENERAL
DEL SEGURO, SUS COBERTURAS Y EL PROCEDIMIENTO A SEGUIR EN CASO DE SINIESTRO. EL RESUMEN DE LOS SEGUROS ES PARCIAL
Y NO REEMPLAZA A LAS CONDICIONES PARTICULARES NI GENERALES DE LAS RESPECTIVAS PÓLIZAS Y SÓLO TIENEN UN
CARÁCTER INFORMATIVO. EN CASO DE REQUERIR UNA COPIA DE LAS CONDICIONES GENERALES Y PARTICULARES DEL SEGURO, EL
CLIENTE DEBE SOLICITARLAS A BCI SEGUROS VIDA S.A.<br>
3- VIGENCIA DE LA PÓLIZA COLECTIVA: EL SEGURO DE VIDA OPERA A TRAVÉS DE UNA PÓLIZA COLECTIVA ÚNICA Y CADA
CERTIFICADO DE SEGURO EMITIDO FORMARÁ PARTE INTEGRANTE DE LA MISMA. LA PÓLIZA COLECTIVA TENDRÁ VIGENCIA DESDE
LAS 00:00 HORAS DEL DÍA 01 DE OCTUBRE DE 2018 HASTA LAS 24:00 HORAS DEL DÍA 30 DE SEPTIEMBRE DE 2019 Y SE
RENOVARÁ TÁCITA Y SUCESIVAMENTE EN LOS MISMOS TÉRMINOS, POR PERIODOS DE 1 AÑO CADA UNO, SALVO VOLUNTAD EN
CONTRARIO DADA POR EL CONTRATANTE O LA ASEGURADORA, SEGÚN CORRESPONDA, POR MEDIO DE CARTA CERTIFICADA
NOTARIAL ENVIADO AL DOMICILIO DE LA PARTE CORRESPONDIENTE.<br>
4- VIGENCIA DE LA PÓLIZA INDIVIDUAL: PARA AQUELLAS PERSONAS QUE CUMPLAN CON LOS REQUISITOS DE ASEGURABILIDAD, LA
COBERTURA COMENZARÁ A REGIR A PARTIR DE LA FECHA DE FIRMA DE LA SOLICITUD DE INCORPORACIÓN Y SE MANTENDRÁ
VIGENTE HASTA LA EXTINCIÓN DEL SÚPER AVANCE QUE LE FUE OTORGADO POR SOLVENTA TARJETAS S.A.<br>
5- ANTE CUALQUIER CONSULTA Y/O RECLAMO PUEDE LLAMAR AL SERVICIO AL CLIENTE DE BCI SEGUROS DESDE TELÉFONO FIJO AL
600 6000 292 O DESDE CELULARES AL 02 2679 9700 DE LUNES A JUEVES DE 08:30 HORAS A 19:00 HORAS, Y VIERNES DE 08:30
HORAS A 17:00 HORAS.

</span>
<br>

<div class="first" style="text-align: center;">DISPOSICIONES FINALES</div>
<br>

<span class="gris" style="text-align: justify"><span class="negrita">CÓDIGO DE AUTORREGULACIÓN
</span><BR>BCI SEGUROS SE ENCUENTRA ADHERIDA AL CÓDIGO DE AUTORREGULACIÓN DE LAS COMPAÑÍAS DE SEGUROS Y ESTÁ SUJETA AL
COMPENDIO DE BUENAS PRÁCTICAS CORPORATIVAS, QUE CONTIENE UN CONJUNTO DE NORMAS DESTINADAS A PROMOVER UNA
ADECUADA RELACIÓN DE LAS COMPAÑÍAS DE SEGUROS CON SUS CLIENTES. COPIA DE ESTE COMPENDIO SE ENCUENTRA EN LA
PÁGINA WEB WWW.AACH.CL.<br>
ASIMISMO, HA ACEPTADO LA INTERVENCIÓN DEL DEFENSOR DEL ASEGURADO CUANDO LOS CLIENTES LE PRESENTEN RECLAMOS EN
RELACIÓN A LOS CONTRATOS CELEBRADOS CON ELLA. LOS CLIENTES PUEDEN PRESENTAR SUS RECLAMOS ANTE EL DEFENSOR DEL
ASEGURADO UTILIZANDO LOS FORMULARIOS DISPONIBLES EN LAS OFICINAS DE BCI SEGUROS O A TRAVÉS DE LA PÁGINA WEB
WWW.DDACHILE.CL
</span>
<br>
<span class="gris" style="text-align: justify"><span class="negrita">INFORMACIÓN SOBRE ATENCIÓN DE CLIENTES Y PRESENTACIÓN DE CONSULTAS Y RECLAMOS
</span><BR>EN VIRTUD DE LA CIRCULAR NRO. 2.131 DE 28 DE NOVIEMBRE DE 2013, LAS COMPAÑÍAS DE SEGUROS, CORREDORES DE SEGUROS Y
LIQUIDADORES DE SINIESTROS, DEBERÁN RECIBIR, REGISTRAR Y RESPONDER TODAS LAS PRESENTACIONES, CONSULTAS O
RECLAMOS QUE SE LES PRESENTEN DIRECTAMENTE POR EL CONTRATANTE, ASEGURADO, BENEFICIARIOS O LEGÍTIMOS
INTERESADOS O SUS MANDATARIOS.<br>
LAS PRESENTACIONES PUEDEN SER EFECTUADAS EN TODAS LAS OFICINAS DE LAS ENTIDADES QUE SE ATIENDA PÚBLICO,
PRESENCIALMENTE, POR CORREO POSTAL, MEDIOS ELECTRÓNICOS, O TELEFÓNICAMENTE, SIN FORMALIDADES, EN EL HORARIO
NORMAL DE ATENCIÓN.<br>
RECIBIDA UNA PRESENTACIÓN, CONSULTA O RECLAMO, ÉSA DEBERÁ SER RESPONDIDA EN EL PLAZO MÁS BREVE POSIBLE, EL QUE
NO PODRÁ EXCEDER DE 20 DIÁS HÁBILES CONTADOS DESDE SU RECEPCIÓN.<br>
INTERESADO, EN CASO DE DISCONFORMIDAD RESPECTO DE LO INFORMADO, O BIEN CUANDO EXISTA DEMORA INJUSTIFICADA DE LA
RESPUESTA, PODRÁ RECURRIR A LA COMISIÓN PARA EL MERCADO FINANCIERO, ÁREA DE PROTECCIÓN AL INVERSIONISTA Y
ASEGURADO, CUYAS OFICINAS SE ENCUENTRAN UBICADAS EN AVDA. LIBERTADOR BERNARDO O'HIGGINS 1449 PISO 1, SANTIAGO, O
A TRAVÉS DEL SITIO WEB WWW.CMFCHILE.CL.
</span>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="first" style="text-align: center">TABLA DE DIVERSIFICACIÓN DE PRODUCCIÓN</div>
<span class="gris" style="text-align: justify;">
	<br>
	INFÓRMESE EN LA COMISIÓN PARA EL MERCADO FINANCIERO SOBRE LA GARANTÍA MEDIANTE BOLETA BANCARIA O PÓLIZA QUE,
CONFORME A LA LEY, DEBEN CONSTITUIR LOS CORREDORES DE SEGUROS.<br>
LA INFORMACIÓN SOBRE LA DIVERSIFICACIÓN DE LOS NEGOCIOS DE ESTA CORREDORA Y DE LAS ENTIDADES ASEGURADORAS CON
QUE HAYA TRABAJADO, ASÍ COMO LA INFORMACIÓN DE LAS PÓLIZAS DE SEGUROS CONTRATADAS PARA RESPONDER DEL
CUMPLIMIENTO DE SUS OBLIGACIONES COMO INTERMEDIARIA Y EN CUMPLIMIENTO A LA LEY Y A LAS INSTRUCCIONES IMPARTIDAS
POR LA COMISIÓN PARA EL MERCADO FINANCIERO, INFORMAMOS QUE DURANTE EL AÑO CALENDARIO ANTERIOR INTERMEDIAMOS
CONTRATOS DE SEGUROS CON LAS COMPAÑÍAS QUE SE INDICAN EN LA FECU 2017 DE ARTHUR J. GALLAGHER CORREDORES DE
SEGUROS S.A. (ART. 57 DFL 251) SON LAS SIGUIENTES:<br>
</span>

<br>
<table border="1" cellpadding="2" class="tablegreen">
	<tr>
			<td><span class="negrita"> COMPAÑÍAS SEGUROS DE VIDA</span></td>
			<td style="text-align: center"><span class="negrita">%</span></td>
			<td> <span class="negrita">COMPAÑÍAS SEGUROS GENERALES </span></td>
			<td style="text-align: center"><span class="negrita">%</span></td>
	</tr>
	<tr>
		<td>BCI SEGUROS VIDA S.A</td>
		<td style="text-align: center">21,7%</td>
		<td>ACE</td>
		<td style="text-align: center">77,8%</td>
	</tr>
	<tr>
		<td>ACE / CHUBB</td>
		<td style="text-align: center">19,8%</td>
		<td>MAPFRE COMPAÑÍA DE SEGUROS GENERALES
DE CHILE S.A.
</td>
		<td style="text-align: center">4,3%</td>
	</tr>
	<tr>
		<td>CHILENA CONSOLIDADA SEGUROS DE VIDA S.A.</td>
		<td style="text-align: center">15,3%</td>
		<td>SEGUROS GENERALES SURAMERICANA S.A.</td>
		<td style="text-align: center">3,7%</td>
	</tr>
	<tr>
		<td>OHIO NATIONAL SEGUROS DE VIDA S.A</td>
		<td style="text-align: center">10,5% </td>
		<td>HDI SEGUROS S.A.</td>
		<td style="text-align: center">3,3%</td>
	</tr>
	<tr>
		<td>COLMENA COMPAÑÍA DE SEGUROS DE VIDA S.A</td>
		<td style="text-align: center">8,5%</td>
		<td>BCI SEGUROS GENERALES S.A.</td>
		<td style="text-align: center">3,0%</td>
	</tr>
	<tr>
		<td>EUROAMERICA SEGUROS DE VIDA S.A.</td>
		<td style="text-align: center">6,4%</td>
		<td>ORION SEGUROS GENERALES S.A.</td>
		<td style="text-align: center">2,8%</td>
	</tr>
	<tr>
		<td>BICE VIDA COMPAÑÍA DE SEGUROS S.A.</td>
		<td style="text-align: center">5,7%</td>
		<td>LIBERTY COMPAÑÍA DE SEGUROS GENERALES
S.A.</td>
		<td style="text-align: center">2,1%</td>
	</tr>
	<tr>
		<td>COMPAÑÍA DE SEGUROS VIDA CÁMARA S.A.</td>
		<td style="text-align: center">4,1%</td>
		<td>AIG</td>
		<td style="text-align: center">2,1%</td>
	</tr>
	<tr>
		<td>SEGUROS VIDA SECURITY PREVISIÓN S.A. </td>
		<td style="text-align: center">2,8%</td>
		<td>CHILENA CONSOLIDADA SEGUROS GENERALES
S.A.</td>
		<td style="text-align: center">0,4%</td>
	</tr>
	<tr>
		<td>METLIFE CHILE SEGUROS DE VIDA S.A.</td>
		<td style="text-align: center">1,7%</td>
		<td>REALE CHILE SEGUROS GENERALES S.A</td>
		<td style="text-align: center">0,3%</td>
	</tr>
	<tr>
		<td>HDI SEGUROS VIDA S.A.</td>
		<td style="text-align: center">1,4%</td>
		<td>CHUBB</td>
		<td style="text-align: center">0,2%</td>
	</tr>
	<tr>
		<td>COMPAÑÍA DE SEGUROS DE VIDA CONSORCIO
NACIONAL DE SEGUROS
</td>
		<td style="text-align: center">1,4%</td>
		<td></td>
		<td style="text-align: center"></td>
	</tr>
	<tr>
		<td>MAPFRE COMPAÑÍA DE SEGUROS DE VIDA DE
CHILE S.A.
</td>
		<td style="text-align: center">0,5%</td>
		<td></td>
		<td style="text-align: center"></td>
	</tr>
	<tr>
		<td><span class="negrita">TOTAL</span></td>
		<td style="text-align: center"><span class="negrita">100%</span></td>
		<td><span class="negrita">TOTAL</span></td>
		<td style="text-align: center"><span class="negrita">100%</span></td>
	</tr>
</table>
<br>
<div class="first" style="text-align: center">ANEXO N°1</div>
<br>
<span class="negrita" style="text-align: center">INFORMACIÓN DE LAS COMISIONES CIRCULAR N° 2123<br>
(COMISIÓN PARA EL MERCADO FINANCIERO)
</span>
<br>
<span class="gris" style="text-align: justify;">DE ACUERDO A LO INSTRUIDO EN LA CIRCULAR N° 2123 DE FECHA DE 22 DE OCTUBRE DE 2013 DE LA COMISIÓN PARA EL MERCADO
FINANCIERO (CMF), LE INFORMAMOS QUE LAS COMISIONES PAGADAS POR BCI SEGUROS VIDA S.A., RESPECTO DE LA PRIMA PAGADA
POR USTED SON LAS SIGUIENTES:</span>
<br>
<table border="1" cellpadding="2" class="tablegreen">
	<tr>
			<td>
				<span class="negrita">COMISIÓN DE INTERMEDIACIÓN</span>
				<br>
				<span class="gris">ARTHUR J. GALLAGHER CORREDORES<br>DE SEGUROS S.A.<br>RUT: 77.682.370-8<br>COMISIÓN: 5% + IVA SOBRE LA<br>PRIMA NETA RECAUDADA.</span>

			</td>
			<td>
				<span class="negrita">COMISIÓN DE RECAUDACIÓN</span>
				<br>
				<span class="gris">SOLVENTA TARJETAS S.A.<br>RUT: 96.776.000-5<br>COMISIÓN: 58,73% (EXENTA DE IVA), SOBRE LA<br>PRIMA NETA RECAUDADA.</span>

			</td>
			<td>
				<span class="negrita">COMISIÓN USO DE CANAL</span>
				<br>
				<span class="gris">SOLVENTA TARJETAS S.A.<br>RUT: 96.776.000-5<br>COMISIÓN: 8,37% + IVA, SOBRE LA<br>PRIMA NETA RECAUDADA.</span>


			</td>
	</tr>
</table>
<br>
<div class="first" style="text-align: center">ANEXO N°2</div>
<br>
<span class="negrita" style="text-align: center;">(CIRCULAR N° 2106 COMISIÓN PARA EL MERCADO FINANCIERO)<br>
PROCEDIMIENTO DE LIQUIDACIÓN DE SINIESTROS</span>
<br>
<span class="gris" style="text-align: justify;">
	<span class="negrita">1) OBJETO DE LA LIQUIDACIÓN</span>
	LA LIQUIDACIÓN TIENE POR FIN ESTABLECER LA OCURRENCIA DE UN SINIESTRO, DETERMINAR SI EL SINIESTRO ESTÁ CUBIERTO EN
LA PÓLIZA CONTRATADA EN UNA COMPAÑÍA DE SEGUROS DETERMINADA, Y CUANTIFICAR EL MONTO DE LA PÉRDIDA Y DE LA
INDEMNIZACIÓN A PAGAR.<br>
EL PROCEDIMIENTO DE LIQUIDACIÓN ESTÁ SOMETIDO A LOS PRINCIPIOS DE CELERIDAD Y ECONOMÍA PROCEDIMENTAL, DE
OBJETIVIDAD Y CARÁCTER TÉCNICO Y DE TRANSPARENCIA Y ACCESO
</span>

<br>
<span class="gris" style="text-align: justify;">
	<span class="negrita">2) FORMA DE EFECTUAR LA LIQUIDACIÓN
</span>
	LA LIQUIDACIÓN PUEDE EFECTUARLA DIRECTAMENTE LA COMPAÑÍA O ENCOMENDARLA A UN LIQUIDADOR DE SEGUROS. LA DECISIÓN
DEBE COMUNICARSE AL ASEGURADO DENTRO DEL PLAZO DE TRES DÍAS HÁBILES CONTADOS DESDE LA FECHA DE LA DENUNCIA
DEL SINIESTRO.
</span>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<span class="gris" style="text-align: justify;">
	<span class="negrita">3) DERECHO DE OPOSICIÓN A LA LIQUIDACIÓN DIRECTA

</span>
	EN CASO DE LIQUIDACIÓN DIRECTA POR LA COMPAÑÍA, EL ASEGURADO O BENEFICIARIO PUEDE OPONERSE A ELLA, SOLICITÁNDOLE
POR ESCRITO QUE DESIGNE UN LIQUIDADOR DE SEGUROS, DENTRO DEL PLAZO DE CINCO DÍAS HÁBILES CONTADOS DESDE LA
NOTIFICACIÓN DE LA COMUNICACIÓN DE LA COMPAÑÍA. LA COMPAÑÍA DEBERÁ DESIGNAR AL LIQUIDADOR EN EL PLAZO DE DOS DÍAS
HÁBILES CONTADOS DESDE DICHA OPOSICIÓN.
</span>
<br>
<span class="gris" style="text-align: justify;">
	<span class="negrita">4) INFORMACIÓN AL ASEGURADO DE GESTIONES A REALIZAR Y PETICION DE ANTECEDENTES

</span>
	EL LIQUIDADOR O LA COMPAÑÍA DEBERÁ INFORMAR AL ASEGURADO, POR ESCRITO, EN FORMA SUFICIENTE Y OPORTUNA, AL
CORREO ELECTRÓNICO (INFORMADO EN LA DENUNCIA DEL SINIESTRO) O POR CARTA CERTIFICADA (AL DOMICILIO SEÑALADO EN LA
DENUNCIA DE SINIESTRO), DE LAS GESTIONES QUE LE CORRESPONDE REALIZAR, SOLICITANDO DE UNA SOLA VEZ, CUANDO LAS
CIRCUNSTANCIAS LO PERMITAN, TODOS LOS ANTECEDENTES QUE REQUIERE PARA LIQUIDAR EL SINIESTRO.
</span>

<br>
<span class="gris" style="text-align: justify;">
	<span class="negrita">5) PRE-INFORME DE LIQUIDACIÓN</span>
	EN AQUELLOS SINIESTROS EN QUE SURGIEREN PROBLEMAS Y DIFERENCIAS DE CRITERIOS SOBRE SUS CAUSAS, EVALUACIÓN DEL
RIESGO O EXTENSIÓN DE LA COBERTURA, PODRÁ EL LIQUIDADOR, ACTUANDO DE OFICIO O A PETICIÓN DEL ASEGURADO, EMITIR UN
PRE-INFORME DE LIQUIDACIÓN SOBRE LA COBERTURA DEL SINIESTRO Y EL MONTO DE LOS DAÑOS PRODUCIDOS, EL QUE DEBERÁ
PONERSE EN CONOCIMIENTO DE LOS INTERESADOS. EL ASEGURADO O LA COMPAÑÍA PODRÁN HACER OBSERVACIONES POR ESCRITO
AL PRE-INFORME DENTRO DEL PLAZO DE CINCO DÍAS HÁBILES DESDE SU CONOCIMIENTO.
</span>

<br>
<br>
<br>
<span class="gris" style="text-align: justify;">
	<span class="negrita">6) PLAZO DE LIQUIDACIÓN</span>
	DENTRO DEL MÁS BREVE PLAZO, NO PUDIENDO EXCEDER DE 45 DÍAS CORRIDOS DESDE FECHA DENUNCIO, A EXCEPCIÓN DE;<br>
A) SINIESTROS QUE CORRESPONDAN A SEGUROS INDIVIDUALES SOBRE RIESGOS DEL PRIMER GRUPO CUYA PRIMA ANUAL SEA
SUPERIOR A 100 UF: 90 DÍASCORRIDOS DESDE FECHA DENUNCIO;<br>
B) SINIESTROS MARÍTIMOS QUE AFECTEN A LOS CASCOS O EN CASO DE AVERÍA GRUESA: 180 DÍAS CORRIDOS DESDE FECHA
DENUNCIO.
</span>

<br>
<span class="gris" style="text-align: justify;">
	<span class="negrita">7) PRORROGA DEL PLAZO DE LIQUIDACIÓN</span>
	LOS PLAZOS ANTES SEÑALADOS PODRÁN, EXCEPCIONALMENTE SIEMPRE QUE LAS CIRCUNSTANCIAS LO AMERITEN, PRORROGARSE,
SUCESIVAMENTE POR IGUALES PERÍODOS, INFORMANDO LOS MOTIVOS QUE LA FUNDAMENTEN E INDICANDO LAS GESTIONES
CONCRETAS Y ESPECÍFICAS QUE SE REALIZARÁN, LO QUE DEBERÁ COMUNICARSE AL ASEGURADO Y A LA COMISIÓN PARA EL
MERCADO FINANCIERO, PUDIENDO ESTA ÚLTIMA DEJAR SIN EFECTO LA AMPLIACIÓN, EN CASOS CALIFICADOS, Y FIJAR UN PLAZO
PARA ENTREGA DEL INFORME DE LIQUIDACIÓN. NO PODRÁ SER MOTIVO DE PRÓRROGA LA SOLICITUD DE NUEVOS ANTECEDENTES
CUYO REQUERIMIENTO PUDO PREVERSE CON ANTERIORIDAD, SALVO QUE SE INDIQUEN LAS RAZONES QUE JUSTIFIQUEN LA FALTA DE
REQUERIMIENTO, NI PODODRÁN PRORROGARSE LOS SINIESTROS EN QUE NO HAYA EXISTIDO GESTIÓN ALGUNA DEL LIQUIDADOR,
REGISTRADO O DIRECTO.
</span>
<br>
<span class="gris" style="text-align: justify;">
	<span class="negrita">8) INFORME FINAL DE LIQUIDACIÓN</span>
	EL INFORME FINAL DE LIQUIDACIÓN DEBERÁ REMITIRSE AL ASEGURADO Y SIMULTÁNEAMENTE AL ASEGURADOR, CUANDO
CORRESPONDA, Y DEBERÁ CONTENER NECESARIAMENTE LA TRANSCRIPCIÓN ÍNTEGRA DE LOS ARTÍCULOS 26 Y 27 DEL
REGLAMENTO DE AUXILIARES DEL COMERCIO DE SEGUROS (D.S. DE HACIENDA N° 1.055, DE 2012, DIARIO OFICIAL DE 29 DE
DICIEMBRE DE 2012).

</span>
<br>
<span class="gris" style="text-align: justify;">
	<span class="negrita">9) IMPUGNACION INFORME DE LIQUIDACIÓN</span>
	RECIBIDO EL INFORME DE LIQUIDACIÓN, LA COMPAÑÍA Y EL ASEGURADO DISPONDRÁN DE UN PLAZO DE DIEZ DÍAS HÁBILES PARA
IMPUGNARLA. EN CASO DE LIQUIDACIÓN DIRECTA POR LA COMPAÑÍA, ESTE DERECHO SÓLO LO TENDRÁ EL ASEGURADO.
IMPUGNADO EL INFORME, EL LIQUIDADOR O LA COMPAÑÍA DISPONDRÁ DE UN PLAZO DE 6 DÍAS HÁBILES PARA RESPONDER LA
IMPUGNACIÓN.
</span>
