<style>

                .first {
                    width:50px;
                      border-top:1px solid #31B404;
                    border-right:1px solid #31B404;
                     border-left:1px solid #31B404;
                       border-bottom:1px solid #31B404;
                       color:#BDBDBD;

                }
                  .second {
                    width:50px;
                      border-top:2px solid black;
                    border-right:1px solid black;
                     border-left:1px solid black;
                       border-bottom:2px solid black;
                       font-size:14px;

                       color:white;
                       background-color:gray;

                }
                .tablegreen td{
					border-collapse: collapse;
					margin:0px;
					border:0.5px solid #31B404;
					color:#BDBDBD;
                }

                .tablegreen th{
					border-collapse: collapse;
					margin:0px;
					border:0.5px solid #31B404;
					color:#BDBDBD;
                }
                .negrita{
                	color:black;
                }
                 .gris{
                	color:#BDBDBD;
                }

                </style>
<table >
	<tr>
		<td valign="baseline" width="120px" style="text-align:left"><img src="/img/firms.documents/logo-bci-vida.jpg" style="width:83px;height:26px;"></td>
		<td valign="baseline" width="230px" style="text-align:center;color:green">SOLICITUD DE INCORPORCIÓN Y CERTIFICADO DE COBERTURA
SEGURO DE ENFERMEDADES GRAVES</td>
		<td valign="baseline" width="160px">
			<table>
			<tr>
			<td valign="baseline" width="100%" style="text-align:right"><img src="/img/firms.documents/logo-solventa-creditos.jpg" style="width:83px;height:26px;"></td>
			</tr>
			<tr>
			<td valign="baseline" width="100%" style="text-align:right;color:green;font-size:9px;">NRO.PÓLIZA: <?= $datos["nroPoliza1"]?></td>
			</tr>
			</table>
		</td>

	</tr>
</table>
<table border="1" cellpadding="2" class="tablegreen">
	<tr>
		<td colspan="1" style="text-align:center;"><b>CERTIFICADO DE COBERTURA – ENFERMEDADES GRAVES</b></td>
	</tr>
	<tr><td width="50px">FECHA</td><td><?= $datos["fecha"] ?> </td></tr>
	<tr>
		<td colspan="1" width="100%" style="font-weight:900;"><b>IDENTIFICACIÓN DEL ASEGURADO TITULAR:</b></td>
	</tr>
	<tr>
		<td colspan="1" width="100%">NOMBRE: <?= $datos["nameClient"]  ?></td>
	</tr>
</table>
<table border="1" cellpadding="2" class="tablegreen">
	<tr>
		<th><b>IDENTIFICACIÓN DEL ASEGURADO TITULAR</b></th>
	</tr>
</table>
<table border="1" cellpadding="2" class="tablegreen">
	<tr>
		<td width="200">FECHA DE NACIMIENTO: <?= $datos["birthDate"] ?> </td>
		<td width="200">RUT: <?= $datos["nroRut"] ."-". $datos["dgvRut"]  ?></td>
<?php if($datos["sexo"]=="MAS"):?>
		<td width="110">SEXO:  F [ ] M [X]  </td>
<?php else: ?>
		<td width="110">SEXO:  F [X] M [ ]  </td>
<?php endif; ?>
	</tr>
</table>

<table border="1" cellpadding="2" class="tablegreen">
	<tr>
		<td width="300">DIRECCIÓN: <?= $datos["calle"] ?> </td>
		<td width="100">Nº: <?= $datos["numCalle"] ?> </td>
		<td width="110">DEPTO/BLOCK: <?= $datos["numDepto"]."/".$datos["block"] ?></td>
	</tr>
</table>

<table border="1" cellpadding="2" class="tablegreen">
	<tr>
		<td>CIUDAD: <?= $datos["ciudad"] ?> </td>
		<td>COMUNA: <?= $datos["comuna"] ?> </td>
		<td>TELEFONO: <?= $datos["fonoFijo"] ?> </td>
		<td>CELULAR: <?= $datos["fonoMovil"] ?> </td>
	</tr>
	<tr>
		<TD colspan="4">CORREO ELECTRÓNICO: <?= $datos["email"] ?></TD>
	</tr>
	<tr>
<?php if($datos["useEmail1"]==1):?>
		<TD colspan="4" style="text-align:justify">AUTORIZO QUE TODA COMUNICACIÓN Y NOTIFICACIÓN QUE DIGA RELACIÓN CON EL PRESENTE SEGURO ME SEA ENVIADA AL
CORREO ELECTRÓNICO SEÑALADO EN ESTA SOLICITUD DE INCORPORACIÓN. SI (X) NO ( ) </TD>
<?php else: ?>
		<TD colspan="4" style="text-align:justify">AUTORIZO QUE TODA COMUNICACIÓN Y NOTIFICACIÓN QUE DIGA RELACIÓN CON EL PRESENTE SEGURO ME SEA ENVIADA AL
CORREO ELECTRÓNICO SEÑALADO EN ESTA SOLICITUD DE INCORPORACIÓN. SI ( ) NO (X) </TD>
<?php endif; ?>
	</tr>
	<tr>
		<td colspan="4" style="text-align:justify">ANTECEDENTES DE LA COMPAÑÍA ASEGURADORA</td>

	</tr>
	<tr>
			<td colspan="2">BCI SEGUROS VIDA S.A</td>
			<td colspan="2">RUT: 96.573.600-K</td>
	</tr>

	<tr>
		<td colspan="4" style="text-align:justify">ANTECEDENTES DEL CONTRATANTE</td>

	</tr>
	<tr>
			<td colspan="2">SOLVENTA TARJETAS S.A.</td>
			<td colspan="2">RUT: 96.776.000-5</td>
	</tr>

	<tr>
		<td colspan="4" style="text-align:justify">ANTECEDENTES DEL CORREDOR</td>

	</tr>
	<tr>
			<td colspan="2">ARTHUR J. GALLAGHER CORREDORES DE SEGUROS S.A.</td>
			<td colspan="2">RUT: 77.682.370-8</td>
	</tr>

	<tr>
		<td colspan="4" style="text-align:center">DATOS DEL SEGURO</td>

	</tr>
	<tr>
			<td colspan="2">MONTO INICIAL DEL SÚPER AVANCE: <?= $datos["montoLiquido"] ?> </td>
			<td colspan="2">NRO. OPERACIÓN: <?= $datos["idDocument"] ?></td>
	</tr>
	<tr>
			<td colspan="2">FECHA INICIO DEL SÚPER AVANCE: <?= $datos["fechaPrimerVencimiento"] ?> </td>
			<td colspan="2">FECHA FIN DEL SÚPER AVANCE: <?= $datos["fechaUltimoVencimiento"] ?></td>
	</tr>
	<tr>
	<td colspan="4">PRIMA ÚNICA DEL SEGURO: $<?= $datos["costoTotalSeguro1"] ?> </td>
	</tr>
	<tr>
		<td colspan="4" style="text-align:center">ASEGURADOS</td>
	</tr>
	<tr>
		<td colspan="4" style="text-align:justify">PERSONAS NATURALES, TARJETAHABIENTES DE TARJETA DE CRÉDITO CRUZ VERDE QUE SOLICITEN UN SÚPER AVANCE, QUE
CUMPLAN LOS REQUISITOS DE ASEGURABILIDAD DETALLADOS EN ESTA COTIZACIÓN.</td>
	</tr>
	<tr>
		<td colspan="4" style="text-align:justify"><span class="negrita">IMPORTANTE:</span> USTED ESTÁ SOLICITANDO SU INCORPORACIÓN COMO ASEGURADO A UNA PÓLIZA O CONTRATO DE SEGURO
COLECTIVO CUYAS CONDICIONES HAN SIDO CONVENIDAS POR SOLVENTA TARJETAS S.A., DIRECTAMENTE CON LA COMPAÑÍA DE
SEGUROS.</td>
	</tr>
</table>
<table  border="1" cellpadding="2" class="tablegreen">
<tr>
	<td style="text-align:center" colspan="1">DETALLE DE COBERTURAS</td>
</tr>
<tr>
	<td style="text-align:center" width="350">COBERTURAS</td>
	<td style="text-align:center">CÓDIGO C.M.F.</td>
</tr>
<tr>
	<td>COBERTURA DE ENFERMEDADES GRAVES </td>
	<td>POL 3 2013 0796</td>
</tr>
</table>
<table  border="1" cellpadding="2" class="tablegreen">
	<tr>
		<td width="410">DECLARACIÓN PERSONAL DE SALUD PARA ENFERMEDADES GRAVES</td>
		<td width="50" style="text-align:center">SI</td>
		<td width="50" style="text-align:center">NO</td>
	</tr>
	<tr>
		<td style="text-align:justify">HA PADECIDO, SE LE HA DIAGNOSTICADO, O TIENE CONOCIMIENTO DE SUFRIR ALGUNA DE LAS SIGUIENTES
ENFERMEDADES: CÁNCER DE CUALQUIER TIPO CON O SIN INVASIÓN, MELANOMA MALIGNO, LEUCEMIA LINFÁTICA,
ENFERMEDADES CARDIACAS, BY-PASS CORONARIO, ENFERMEDADES A LAS CORONARIAS, SOPLOS CARDIACOS,
ARRITMIAS, ENFERMEDADES NEUROLÓGICAS, ACCIDENTE VASCULAR CEREBRAL, EPILEPSIA, ANEURISMAS Y/O
TUMOR CEREBRAL, ENFERMEDADES CRÓNICAS AL HÍGADO, PÁNCREAS, RIÑONES, PULMONES, CORAZÓN, MÉDULA
ÓSEA
</td>
		<td style="text-align:center"></td>
		<td style="text-align:center">X</td>
	</tr>
</table>
<span class="verde">SI RESPONDE SI,</span> <span class="gris">NO SE PUEDE CONTINUAR CON LA VENTA DEL SEGURO.</span>
<br>
<div class="first">SOLICITUD DE INCORPORACIÓN, MANDATO Y AUTORIZACIÓN DE CARGO EN SÚPER AVANCE.</div>
<span class="gris" style="text-align:justify">MEDIANTE LA PRESENTE SOLICITUD DE INCORPORACIÓN Y CERTIFICADO DE COBERTURA SOLICITO SER INCORPORADO A ESTA
PÓLIZA COLECTIVA CUYOS TÉRMINOS, NATURALEZA, CONDICIONES DE ASEGURABILIDAD, COBERTURA, VIGENCIA, EXCLUSIONES,
COMISIONES Y DEMÁS CARACTERÍSTICAS DECLARO CONOCER A CABALIDAD POR HABERME SIDO EXPLICADAS Y POR HABER TENIDO
A LA VISTA, PREVIO A MI FIRMA, EL CERTIFICADO DE COBERTURA Y, LAS CONDICIONES PARTICULARES Y GENERALES QUE SE
DETALLAN SUFICIENTEMENTE. DECLARO ADEMÁS, QUE CONTRATO VOLUNTARIO E INFORMADAMENTE ESTE SEGURO. ASIMISMO
OTORGO MANDATO Y FACULTO A SOLVENTA TARJETAS S.A. PARA INCORPORARME EN CALIDAD DE ASEGURADO, A LA PÓLIZA
COLECTIVA: <?= $datos["nroPoliza1"]?> Y AGREGAR EL VALOR DE LA PRIMA ÚNICA, AL MONTO DEL SÚPER AVANCE QUE ME HA SIDO OTORGADO POR
SOLVENTA TARJETAS S.A. EL MANDATARIO RENDIRÁ CUENTA DE SU MANDATO ENTREGÁNDOLE AL ASEGURADO AL MOMENTO DE
CONTRATAR EL SÚPER AVANCE UNA LIQUIDACIÓN DEL SÚPER AVANCE, EN DONDE SE INDIQUE EL CARGO DE LA PRIMA
CORRESPONDIENTE. EL CLIENTE ASEGURABLE AUTORIZA A SOLVENTA TARJETAS S.A. Y A LA COMPAÑÍA ASEGURADORA, PARA
QUE LOS DATOS SUMINISTRADOS SEAN UTILIZADOS PARA LA ADMINISTRACIÓN Y AUDITORÍA DEL SEGURO CONTRATADO, EL
OFRECIMIENTO DE OTROS SEGUROS U OTROS SÚPER AVANCE EN LOS QUE PUDIERE ESTAR INTERESADO.
MEDIANTE LA SIGUIENTE FIRMA, ACEPTO LA CONTRATACIÓN DE ESTE SEGURO.
</span>
<div style="text-align:center"><img src="/img/firms.documents/firm1-seguros.png" style="width:687px;height:144px;"></div>
<br>
<div class="first" style="text-align: center">
	DESCRIPCIÓN DE COBERTURAS Y CONDICIONES DE ASEGURABILIDAD
</div>
<br>
<span class="negrita">MATERIA Y MONTO ASEGURADO</span>
<span class="gris" style="text-align: justify">SE ESTABLECE UN TOPE DE INDEMNIZACIÓN IGUAL A UF 180, POR ASEGURADO, EN EL CASO DE SÚPER AVANCE. LAS
ENFERMEDADES GRAVES CUBIERTAS SON LAS SIGUIENTES:</span>
<br>
<span class="gris" style="text-align: justify"><span class="negrita">CÁNCER:</span>:LA PRESENCIA DE UNO O MÁS TUMORES MALIGNOS, INCLUYENDO ENTRE ELLOS LOS DIVERSOS TIPOS DE LEUCEMIA
(EXCEPTO LA LEUCEMIA LINFOCITICO CRÓNICA) LOS LINFOMAS Y LA ENFERMEDAD DE HODGKIN; CARACTERIZADOS POR EL
CRECIMIENTO INCONTROLADO, LA DISEMINACIÓN DE CÉLULAS MALIGNAS Y LA INVASIÓN Y DESTRUCCIÓN DE TEJIDOS NORMALES. EL
DIAGNÓSTICO DEBERÁ HABER SIDO HECHO POR UN MÉDICO ONCÓLOGO.
LOS SIGUIENTES CÁNCERES NO ESTÁN CUBIERTOS POR LA PÓLIZA: A. TUMORES QUE PRESENTEN LOS CAMBIOS MALIGNOS
CARACTERÍSTICOS DE CARCINOMA IN SITU (INCLUYENDO LA DISPLASIA CERVICAL CIN-1, CIN-2 Y CIN-3) O AQUELLOS
CONSIDERADOS POR HISTOLOGÍA COMO PREMALIGNOS; B. MELANOMAS CON ESPESOR MENOR DE 1,5 MM, DETERMINADO POR
EXAMEN HISTOLÓGICO, O CUANDO LA INVASIÓN SEA MENOR DEL NIVEL DE CLARK 3; C. TODAS LAS HIPERQUERATOSIS O LOS
CARCINOMAS BASOCELULARES DE LA PIEL; D. TODOS LOS CARCINOMAS DE PIEL, CÉLULAS ESCAMOSAS, EXCEPTO CUANDO SE
TRATE DE DISEMINACIÓN DE OTROS ÓRGANOS; E. SARCOMA DE KAPOSI Y OTROS TUMORES RELACIONADOS CON LA INFECCIÓN VIH O
SIDA; F. CÁNCERES DE LA PRÓSTATA QUE POR HISTOLOGÍA PERTENEZCAN A LA ETAPA T1 DEL SISTEMA TNM, DESARROLLADO POR
LA UNIÓN INTERNACIONAL CONTRA EL CÁNCER (INCLUYENDO T1 (A) O T1 (B) O DE CUALQUIER OTRA CLASIFICACIÓN EQUIVALENTE O
MENOR).
</span>
<br>
<span class="gris" style="text-align: justify"><span class="negrita">INFARTO DEL MIOCARDIO:</span>:LA MUERTE DE UNA PORCIÓN DEL MÚSCULO CARDIACO, CAUSADA POR IRRIGACIÓN INADECUADA DE LA
PARTE AFECTADA Y PUESTA DE MANIFIESTO POR EL TÍPICO DOLOR DEL PECHO, LA APARICIÓN DE MODIFICACIONES
ELECTROCARDIOGRÁFICAS QUE NO EXISTÍAN (NUEVAS) Y ELEVACIÓN DE LAS ENZIMAS CARDIACAS.
</span>
<br>
<span class="gris" style="text-align: justify"><span class="negrita">ACCIDENTE VASCULAR CEREBRAL:</span>CUALQUIER INCIDENTE CEREBROVASCULAR QUE DÉ LUGAR A SECUELAS QUE DURE MÁS DE
VEINTICUATRO (24) HORAS Y QUE INCLUYAN INFARTO DEL TEJIDO CEREBRAL, HEMORRAGIA Y EMBOLISMO, TODOS DE UNA FUENTE
EXTRA CRANEANA. LA EVIDENCIA DEL DAÑO NEUROLÓGICO PERMANENTE DEBERÁ SER CONFIRMADA POR UN NEURÓLOGO, COMO
MÍNIMO DOCE (12) SEMANAS DESPUÉS DEL SUCESO. NO SE ACEPTARÁN RECLAMACIONES ANTES DE TRANSCURRIDO ESE TIEMPO.
NO SE CONSIDERARÁN DENTRO DE LA COBERTURA LOS SÍNTOMAS CEREBRALES DE MIGRAÑA, LESIÓN CEREBRAL CAUSADA POR UN
TRAUMATISMO O HIPOXIA Y ENFERMEDAD VASCULAR QUE AFECTE AL OJO O AL NERVIO ÓPTICO, Y LAS ALTERACIONES
ISQUÉMICAS DEL SISTEMA VESTIBULAR
</span>
<br>
<span class="gris" style="text-align: justify"><span class="negrita">INSUFICIENCIA RENAL CRÓNICA:</span>LA ETAPA FINAL DE LA INSUFICIENCIA RENAL, POR FALLO FUNCIONAL, CRÓNICO E IRREVERSIBLE
DE AMBOS RIÑONES, QUE HACE NECESARIA LA DIÁLISIS RENAL SISTEMÁTICA O EL TRASPLANTE RENAL.
</span>
<br>
<span class="gris" style="text-align: justify"><span class="negrita">REVASCULARIZACIÓN CORONARIA (BY-PASS):</span>COMPRENDE LA QUE SE REALIZA AL MENOS A DOS O MÁS ARTERIAS CORONARIAS,
POR CONSEJO DE UN MÉDICO ESPECIALISTA EN ESTA CIRUGÍA, PARA CORREGIR LA ESTENOSIS U OCLUSIÓN DE LAS ARTERIAS
CORONARIAS, PERO QUEDAN EXCLUIDAS LAS TÉCNICAS NO OPERATORIAS MEDIANTE CIRUGÍA, COMO LA ANGIOPLASTIA, EL
TRATAMIENTO POR LÁSER O CUALQUIER OTRO PROCEDIMIENTO NO OPERATORIO.
</span>
<br>
<span class="gris" style="text-align: justify"><span class="negrita">TRANSPLANTE DE ÓRGANOS MAYORES:</span>:EL QUE SE REALIZA AL ASEGURADO COMO RECEPTOR DEL TRASPLANTE DE UN ÓRGANO
QUE PUEDE SER CUALQUIERA DE LOS SIGUIENTES: CORAZÓN, PULMÓN, HÍGADO, RIÑÓN, MÉDULA ÓSEA O PÁNCREAS, SIEMPRE Y
CUANDO EL ÓRGANO DEL ASEGURADO ESTÉ O HAYA ESTADO LESIONADO O ENFERMO. LA COBERTURA SÓLO COMPRENDE EL
TRASPLANTE DE TODO EL ÓRGANO Y NO DE FRACCIONES O PARTES DE ÉSTE, POR LO QUE EN EL CASO DEL PÁNCREAS SE EXCLUYE
EL TRASPLANTE DE ISLOTES DE LANGERHANS. NO ESTARÁ CUBIERTO EL TRASPLANTE AUTÓLOGO. SERÁ REQUISITO
INDISPENSABLE PARA EL PAGO DEL BENEFICIO QUE EL ASEGURADO NOTIFIQUE PREVIAMENTE Y POR ESCRITO A LA COMPAÑÍA
ASEGURADORA EL HECHO DE SER DEFINIDO COMO CANDIDATO A TRASPLANTE POR LA INSTITUCIÓN HOSPITALARIA O REGULADORA
CORRESPONDIENTE Y ANTES QUE ÉSTE SE REALICE. UNA VEZ QUE LA COMPAÑÍA HA SIDO NOTIFICADA DE ESTE HECHO SÓLO
PODRÁ PONER TÉRMINO AL CONTRATO DEL ASEGURADO QUE SE ENCUENTRE EN DICHA SITUACIÓN SI ÉSTE INCURRIERE EN ALGUNA
CAUSAL LEGAL QUE ASÍ LO PERMITA.</span>
<br>
<span class="gris" style="text-align: justify"><span class="negrita">ESCLEROSIS MÚLTIPLE:</span>DIAGNÓSTICO INEQUÍVOCO DE ESCLEROSIS MÚLTIPLE, HECHO POR UN NEURÓLOGO, EN QUE EL PACIENTE
DEBA SER INTERNADO EN UN HOSPITAL POR ESTA CAUSA. DEBERÁ HABER EVIDENCIA DE LOS SÍNTOMAS CARACTERÍSTICOS DE
DESMIELINIZACIÓN, DE ANORMALIDADES NEUROLÓGICAS PERSISTENTES Y DE DETERIORO FUNCIONAL. EL DIAGNÓSTICO DEBERÁ
CONFIRMARSE POR INVESTIGACIONES NEUROLÓGICAS (EJEMPLO: PUNCIÓN LUMBAR, RESPUESTAS AUDITIVAS Y VISUALES
EVOCADAS Y EVIDENCIA DE LESIONES DEL SISTEMA NERVIOSO CENTRAL).</span>
<br>
<span class="gris" style="text-align: justify"><span class="negrita">PARÁLISIS:</span>PARÁLISIS TOTAL Y PERMANENTE, PRODUCIDA POR ACCIDENTE O ENFERMEDAD. DEBERÁ HABER EVIDENCIA DEL FALLO
TOTAL Y PERMANENTE DE LA CONDUCTIVIDAD DE LA MÉDULA ESPINAL POR SECCIÓN MEDULAR. LA CONEXIÓN DE TIEMPO Y CAUSA
CON EL DAÑO DEBERÁ SER OBVIA.</span>
<br>
<span class="gris" style="text-align: justify"><span class="negrita">DISTROFIA MUSCULAR:</span>LA DISTROFIA MUSCULAR SE DEFINE COMO UN GRUPO DE MIOPATÍAS GENÉTICAS DEGENERATIVAS, QUE SE
CARACTERIZAN POR DEBILIDAD Y ATROFIA MUSCULAR, SIN PARTICIPACIÓN DEL SISTEMA NERVIOSO. LOS DIVERSOS TIPOS SE
DISTINGUEN POR EL PRINCIPIO, LOCALIZACIÓN Y EVOLUCIÓN DE LA ENFERMEDAD.</span>
<br>
<span class="gris" style="text-align: justify"><span class="negrita">INTERÉS ASEGURABLE:</span><BR>EL INTERÉS ASEGURABLE ES LA PÉRDIDA DEL ASEGURADO DE GENERAR INGRESOS A CAUSA DE SU PÉRDIDA DE CAPACIDAD DE
TRABAJO, PRODUCTO DE HABER SIDO DIAGNOSTICADO DE ALGUNA DE LAS ENFERMEDADES DESCRITAS O HABERSE PRACTICADO
ALGUNO DE LOS PROCEDIMIENTOS CUBIERTOS POR LA PRESENTE PÓLIZA.</span>
<BR>
<span class="gris" style="text-align: justify"><span class="negrita">REQUISITOS DE ASEGURABILIDAD</span></span>
<br>
<table border="1" cellpadding="2" class="tablegreen" style="text-align: center">
	<tr>
			<td>EDAD MÍNIMA DE INGRESO: 18AÑOS.</td>
			<td>EDAD MÁXIMA DE INGRESO: 74 AÑOS Y 364 DÍAS</td>
			<td>EDAD MÁXIMA DE COBERTURA: 79 AÑOS Y 364 DÍAS.</td>
	</tr>
</table>
<BR>
<span class="gris" style="text-align: justify">LA EDAD DE INGRESO DEL ASEGURADO MÁS EL PLAZO DEL SÚPER AVANCE NO DEBEN SUPERAR LA EDAD DE PERMANENCIA.
SOLAMENTE SE INDEMNIZARÁ LA PRIMERA ENFERMEDAD O INTERVENCIÓN QUIRÚRGICA, CUBIERTA, QUE SEA DIAGNOSTICADA
DESPUÉS DE FINALIZADO EL PERÍODO DE CARENCIA, Y DURANTE LA VIGENCIA DE LA COBERTURA.
</span>
<br>
<span class="gris" style="text-align: justify"><span class="negrita">CARENCIA</span><BR>90 DÍAS CORRIDOS DESDE EL INICIO DE LA VIGENCIA DE LA COBERTURA.</span>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<span class="gris" style="text-align: justify"><span class="negrita">BENEFICIARIOS</span><BR>MIENTRAS EL SÚPER AVANCE OTORGADO AL ASEGURADO SE ENCUENTRE VIGENTE, EL BENEFICIARIO SERÁ SOLVENTA TARJETAS
S.A., POR UN MONTO EQUIVALENTE AL SALDO INSOLUTO DEL SÚPER AVANCE, Y A SU VEZ, LA DIFERENCIA RESTANTE ENTRE EL
SALDO INSOLUTO Y EL MONTO INICIAL DEL SÚPER AVANCE SERÁ ENTREGADA AL ASEGURADO TITULAR.
EN CASO QUE EL SÚPER AVANCE NO SE ENCUENTRE VIGENTE, EL BENEFICIARIO SERÁ EL ASEGURADO TITULAR, A QUIEN SE
INDEMNIZARÁ POR UN MONTO EQUIVALENTE AL CAPITAL INICIAL DEL SÚPER AVANCE SOLICITADO.
PARA ESTOS EFECTOS EL SALDO INSOLUTO DEL SÚPER AVANCE, SERÁ EL VIGENTE AL ÚLTIMO DÍA DEL MES INMEDIATAMENTE
ANTERIOR A LA FECHA DE OCURRENCIA DEL SINIESTRO, SOBRE LA BASE DE UN SERVICIO REGULAR DE LA DEUDA; ESTO ES, QUE EL
ASEGURADO TENGA TODAS Y CADA UNA DE LAS CUOTAS PAGADAS DEL SÚPER AVANCE AL DÍA PRECEDENTEMENTE SEÑALADO.
MONTO INICIAL DEL SÚPER AVANCE SE ENTENDERÁ EL MONTO LÍQUIDO ENTREGADO AL ASEGURADO A TÍTULO DE SÚPER AVANCE
OTORGADO POR SOLVENTA TARJETAS S.A.</span>
<br>
<span class="gris" style="text-align: justify"><span class="negrita">COBERTURA DE ENFERMEDADES GRAVES (POL 3 2013 0796, ARTÍCULO 2)</span><BR>LA COMPAÑÍA ASEGURADORA PAGARÁ LA SUMA ASEGURADA SI DESPUÉS DEL PERÍODO DE CARENCIA Y DENTRO DE LA VIGENCIA
DEL SEGURO, AL ASEGURADO SE LE DIAGNOSTICA POR PRIMERA VEZ UNA ENFERMEDAD O ES SOMETIDO A UNA INTERVENCIÓN
QUIRÚRGICA, DE AQUELLAS CUBIERTAS POR ESTA PÓLIZA. SERÁN ASEGURABLES LAS PERSONAS MENORES DE SETENTA Y CUATRO
AÑOS Y TRECIENTOS SESENTA Y CUATRO DÍAS DE EDAD (74 AÑOS Y 364 DÍAS), QUE LLENEN UNA DECLARACIÓN PERSONAL DE
SALUD, CUANDO CORRESPONDA, Y QUE SEAN ACEPTADOS POR LA COMPAÑÍA ASEGURADORA. EN LOS CASOS DE RENOVACIÓN EL
ASEGURADO GOZARÁ DE COBERTURA HASTA LA EDAD O EL PERIODO QUE SE ESPECIFIQUE EN LAS CONDICIONES PARTICULARES</span>
<br>
<span class="gris" style="text-align: justify"><span class="negrita">PLAZO DE COBERTURA
</span><BR>ESTE SEGURO TENDRÁ UNA DURACIÓN DE 12 MESES A PARTIR DE SU CONTRATACIÓN, FINALIZADO DICHO PLAZO SE TERMINA LA
PÓLIZA. EL SEGURO NO TIENE RENOVACIÓN AUTOMÁTICA.<br>
MIENTRAS EL SÚPER AVANCE SE ENCUENTRE VIGENTE, EL BENEFICIARIO SERÁ SOLVENTA TARJETAS S.A., CUYO CAPITAL A
INDEMNIZAR SERÁ EL SALDO INSOLUTO DE LA DEUDA AL MES INMEDIATAMENTE POSTERIOR DE REALIZADO EL DIAGNOSTICO O
HABERSE PRACTICADO ALGUNO DE LOS PROCEDIMIENTOS CUBIERTOS POR LA PRESENTE PÓLIZA.<br>
ESTE SEGURO DE ENFERMEDADES GRAVES SÓLO SE PODRÁ CONTRATAR AL MOMENTO DE SOLICITAR UN SÚPER AVANCE Y SU
VIGENCIA SERÁ POR 12 MESES (INDEPENDIENTE DEL PLAZO DEL SÚPER AVANCE), FINALIZADO DICHO PLAZO SE TERMINA LA
PÓLIZA.</span>
<br>
<span class="gris" style="text-align: justify"><span class="negrita">PRIMA DEL SEGURO
</span><BR>LA PRIMA SERÁ DE PERIODICIDAD ÚNICA Y SE CALCULARÁ EN FUNCIÓN DE UNA TASA ÚNICA, IGUAL A 13% + IVA, APLICADA SOBRE
EL MONTO INICIAL DEL SÚPER AVANCE, ENTENDIÉNDOSE POR TAL, EL MONTO LÍQUIDO QUE ES ENTREGADO AL ASEGURADO EN EL
SÚPER AVANCE OTORGADO POR SOLVENTA TARJETAS S.A. (SE CONSIDERA UNA PRIMA TOPE IGUAL A $238.000, IVA INCLUIDO)</span>
<br>
<div class="first" style="text-align: center">EXCLUSIONES</div>
<br>
<span class="negrita">EXCLUSIONES COBERTURA DE ENFERMEDADES GRAVES (POL 3 2013 0796, ARTÍCULO 6)</span>
<br>
<span class="gris" style="text-align: justify;">ADEMÁS DE LAS EXCLUSIONES CONTENIDAS EN LAS DEFINICIONES Y DESCRIPCIÓN DE LAS ENFERMEDADES SEÑALADAS EN EL
ARTÍCULO 3 DEL POL 3 2013 0796, NO ESTARÁN CUBIERTAS POR LA PÓLIZA LAS SITUACIONES O ENFERMEDADES QUE TENGAN SU
CAUSA MEDIATA O INMEDIATA EN ALGUNO DE LOS SIGUIENTES HECHOS:<br>
A. SIDA O PRESENCIA DEL VIRUS VIH;<br>
B. LEUCEMIA LINFOCÍTICA CRÓNICA;<br>
C. SUICIDIO, TENTATIVA DE SUICIDIO O ENFERMEDAD INTENCIONALMENTE CAUSADA O LESIONES AUTOINFLINGIDAS, YA SEA EN
ESTADO DE CORDURA O DEMENCIA;<br>
D. RIÑAS O ALBOROTOS POPULARES EN LOS QUE HUBIERE INTERVENIDO EL ASEGURADO;<br>
E. RIESGOS NUCLEARES;<br>
F. PADECIMIENTOS CONGÉNITOS;<br>
G. TRASPLANTES QUE SEAN PROCEDIMIENTOS DE INVESTIGACIÓN;<br>
H. INTOXICACIÓN O ENCONTRARSE EL ASEGURADO EN ESTADO DE EBRIEDAD, O BAJO LOS EFECTOS DE CUALQUIER NARCÓTICO O
DROGA A MENOS QUE HUBIESE SIDO ADMINISTRADO POR PRESCRIPCIÓN MÉDICA. PARA LOS EFECTOS DE LA PRESENTE EXCLUSIÓN,
SE CONSIDERARÁ QUE EL ASEGURADO SE ENCONTRABA EN ESTADO DE EBRIEDAD, CUANDO LA CONCENTRACIÓN DE ALCOHOL EN LA
SANGRE SEA IGUAL O SUPERIOR A 1,00 GRAMO DE ALCOHOL POR LITRO DE SANGRE. LOS ESTADOS A QUE SE REFIERE LA PRESENTE
EXCLUSIÓN SE ACREDITARÁN MEDIANTE LA DOCUMENTACIÓN EXPEDIDA POR LOS ORGANISMOS CORRESPONDIENTES;<br>
I. SITUACIONES O ENFERMEDADES PREEXISTENTES. PARA LOS EFECTOS DE LA APLICACIÓN DE ESTA EXCLUSIÓN, AL MOMENTO DE
LA CONTRATACIÓN LA COMPAÑÍA ASEGURADORA DEBERÁ CONSULTAR AL ASEGURABLE ACERCA DE TODAS AQUELLAS
SITUACIONES O ENFERMEDADES PREEXISTENTES QUE PUEDEN IMPORTAR UNA LIMITACIÓN O EXCLUSIÓN DE COBERTURA. EN EL
CERTIFICADO DE COBERTURA O EN LAS CONDICIONES PARTICULARES DE LA PÓLIZA, SEGÚN CORRESPONDA, SE ESTABLECERÁN LAS
EXCLUSIONES, RESTRICCIONES Y LIMITACIONES DE LA COBERTURA EN VIRTUD DE LA DECLARACIÓN DE SALUD EFECTUADA POR EL
ASEGURABLE</span>
<br>
<div class="first" style="text-align: center">PROCEDIMIENTO DE DENUNCIA DE SINIESTRO</div>
<br>
<span class="gris" style="text-align: justify;">
	EN CASO DE CONSULTAS, RECLAMOS Y DENUNCIAS DE SINIESTRO, EL ASEGURADO SE DEBERÁ COMUNICAR AL TELÉFONO DEL
CENTRO DE RESPUESTA INMEDIATA (CRI) DE LA COMPAÑÍA DE SEGUROS 600 6000 292 - DESDE CELULAR 2 2679 9700 O EN
CUALQUIERA DE LAS OFICINAS DE BCI SEGUROS VIDA S.A.<br>
EN TODOS LOS CASOS LA COMPAÑÍA SE RESERVA EL DERECHO DE PEDIR MAYORES ANTECEDENTES PARA LA LIQUIDACIÓN DEL
SINIESTRO. EN TODAS LAS DENUNCIAS DEBERÁ DEJARSE CONSTANCIA DEL NOMBRE, DIRECCIÓN Y TELÉFONO DE LA PERSONA
DENUNCIANTE PARA POSTERIORES CONTACTOS QUE SEAN NECESARIOS.<br>
PRODUCIDO EL DIAGNÓSTICO, ACCIDENTE O LA PRÁCTICA DE LA INTERVENCIÓN, EL ASEGURADO O ALGUNA PERSONA POR ÉL
DESIGNADA DEBERÁN COMUNICARLO POR ESCRITO A LA COMPAÑÍA DENTRO DE UN PLAZO DE SESENTA (60) DÍAS CORRIDOS. EL
CUMPLIMIENTO EXTEMPORÁNEO DE ESTA OBLIGACIÓNHARÁ PERDER EL DERECHO A LA INDEMNIZACIÓN ESTABLECIDA EN LA
PRESENTE PÓLIZA, PARA LO ANTERIOR DEBERÁ PRESENTAR:	<br>
<ul>
		<li>FOTOCOPIA DE LA CÉDULA DE IDENTIDAD DEL ASEGURADO POR AMBOS LADOS.</li>
		<br>
		<br>
			<br>
		<br>
			<br>
		<br>
		<li>FICHA CLÍNICA AMBULATORIA Y/O HOSPITALARIA COMPLETA</li>
		<li>EPICRISIS, CERTIFICADOS, INFORMES Y EXÁMENES MÉDICOS QUE ACREDITEN LA ENFERMEDAD O REALIZACIÓN DE
INTERVENCIONES Y /O PROCEDIMIENTOS CUBIERTOS.</li>
		<li>RESULTADO DE ANATOMÍA PATOLÓGICA (BIOPSIA) PARA LA COBERTURA DE CÁNCER</li>
</ul>
<br>
<br>
EN CASO DE NO EXISTIR BENEFICIARIOS DESIGNADOS SE DEBERÁ PRESENTAR:
<br>
EN TODOS LOS CASOS LA COMPAÑÍA SE RESERVA EL DERECHO DE PEDIR MAYORES ANTECEDENTES PARA LA LIQUIDACIÓN DEL
SINIESTRO.<br>
EN TODAS LAS DENUNCIAS DEBERÁ DEJARSE CONSTANCIA DEL NOMBRE, DIRECCIÓN Y TELÉFONO DE LA PERSONA DENUNCIANTE
PARA POSTERIORES CONTACTOS QUE SEAN NECESARIOS.
</span>
<br>
<br>
<div class="first" style="text-align: center">NOTAS IMPORTANTES</div>
<br>
<span class="gris" style="text-align: justify;">
	1-  EL ASEGURADO DECLARA ESTAR EN CONOCIMIENTO DE; A) EL ASEGURADO DECLARA CONOCER, HABER SIDO PREVIA Y
COMPLETAMENTE INFORMADO Y ACEPTAR LAS CONDICIONES SEÑALADAS EN ESTA SOLICITUD DE INCORPORACIÓN Y CERTIFICADO
DE COBERTURA ANTES DE FIRMARLA EN SEÑAL DE ACEPTACIÓN. B) EL ASEGURADO HA TOMADO CONOCIMIENTO DEL DERECHO A
DECIDIR SOBRE LA CONTRATACIÓN VOLUNTARIA DEL SEGURO Y LA LIBRE ELECCIÓN DE LA COMPAÑÍA ASEGURADORA. C) EL
CONTRATANTE COLECTIVO DE LA PÓLIZA N° <?= $datos["nroPoliza1"]?> SERÁ SOLVENTA TARJETAS S.A. D) LAS COBERTURAS TENDRÁN VIGENCIA
DESDE LA FIRMA DEL ASEGURADO. EN ESTE CASO LA PRESENTE SOLICITUD HARÁ LAS VECES DE CERTIFICADO DE COBERTURA
CONFORME A LA CIRCULAR N° 2123 DE LA COMISIÓN PARA EL MERCADO FINANCIERO
<br>
2- LA PRESENTE SOLICITUD ES UN RESUMEN CON LA DESCRIPCIÓN GENERAL DE LAS COBERTURAS Y EL PROCEDIMIENTO A SEGUIR
EN CASO DE SINIESTRO. EL RESUMEN DEL SEGURO ES PARCIAL Y NO REEMPLAZA A LAS CONDICIONES PARTICULARES NI
GENERALES DE LA RESPECTIVA PÓLIZA Y SÓLO TIENE UN CARÁCTER INFORMATIVO. EN CASO DE REQUERIR UNA COPIA DE LAS
CONDICIONES GENERALES Y PARTICULARES DEL SEGURO, EL CLIENTE DEBE SOLICITARLAS A BCI SEGUROS VIDA S.A.
<br>
3- VIGENCIA DE LA PÓLIZA COLECTIVA: LA PÓLIZA COLECTIVA TENDRÁ VIGENCIA DESDE LAS 00:00 HORAS DEL DÍA 01 DE
OCTUBRE DE 2018 HASTA LAS 24:00 HORAS DEL DÍA 30 DE SEPTIEMBRE DE 2019 Y SE RENOVARÁ TÁCITA Y SUCESIVAMENTE EN
LOS MISMOS TÉRMINOS, POR PERIODOS DE 1 AÑO CADA UNO, SALVO VOLUNTAD EN CONTRARIO DADA POR EL CONTRATANTE O LA
ASEGURADORA, SEGÚN CORRESPONDA, POR MEDIO DE CARTA CERTIFICADA NOTARIAL ENVIADO AL DOMICILIO DE LA PARTE
CORRESPONDIENTE.
<br>
4- VIGENCIA DE LA PÓLIZA INDIVIDUAL: PARA AQUELLAS PERSONAS QUE CUMPLAN CON LOS REQUISITOS DE ASEGURABILIDAD, LA
COBERTURA COMENZARÁ A REGIR A PARTIR DE LA FECHA DE FIRMA DE LA SOLICITUD DE INCORPORACIÓN Y CERTIFICADO DE
COBERTURA, Y SE MANTENDRÁ VIGENTE POR LOS PRIMEROS 12 MESES QUE PACTO PARA EL PAGO DEL SÚPER AVANCE QUE LE
OTORGÓ SOLVENTA TARJETAS S.A.
<br>
5- ANTE CUALQUIER CONSULTA Y/O RECLAMO PUEDE LLAMAR AL SERVICIO AL CLIENTE DE BCI SEGUROS DESDE TELÉFONO FIJO AL
600 6000 292 O DESDE CELULARES AL 02 2679 9700 DE LUNES A JUEVES DE 08:30 HORAS A 19:00 HORAS, Y VIERNES DE 08:30
HORAS A 17:00 HORAS.

</span>
<div class="first" style="text-align: center">DISPOSICIONES FINALES</div>
<br>
<span class="negrita">CÓDIGO DE AUTORREGULACIÓN</span>
<br>
<span class="gris" style="text-align: justify;">
		BCI SEGUROS SE ENCUENTRA ADHERIDA AL CÓDIGO DE AUTORREGULACIÓN DE LAS COMPAÑÍAS DE SEGUROS Y ESTÁ SUJETA AL
COMPENDIO DE BUENAS PRÁCTICAS CORPORATIVAS, QUE CONTIENE UN CONJUNTO DE NORMAS DESTINADAS A PROMOVER UNA
ADECUADA RELACIÓN DE LAS COMPAÑÍAS DE SEGUROS CON SUS CLIENTES. COPIA DE ESTE COMPENDIO SE ENCUENTRA EN LA
PÁGINA WEB WWW.AACH.CL.<br>
ASIMISMO, HA ACEPTADO LA INTERVENCIÓN DEL DEFENSOR DEL ASEGURADO CUANDO LOS CLIENTES LE PRESENTEN RECLAMOS EN
RELACIÓN A LOS CONTRATOS CELEBRADOS CON ELLA. LOS CLIENTES PUEDEN PRESENTAR SUS RECLAMOS ANTE EL DEFENSOR DEL
ASEGURADO UTILIZANDO LOS FORMULARIOS DISPONIBLES EN LAS OFICINAS DE BCI SEGUROS O A TRAVÉS DE LA PÁGINA WEB
WWW.DDACHILE.CL

</span>
<br>
<span class="negrita">INFORMACIÓN SOBRE ATENCIÓN DE CLIENTES Y PRESENTACIÓN DE CONSULTAS Y RECLAMOS</span>
<br>
<span class="gris" style="text-align: justify;">
		EN VIRTUD DE LA CIRCULAR NRO. 2.131 DE 28 DE NOVIEMBRE DE 2013, LAS COMPAÑÍAS DE SEGUROS, CORREDORES DE SEGUROS Y
LIQUIDADORES DE SINIESTROS, DEBERÁN RECIBIR, REGISTRAR Y RESPONDER TODAS LAS PRESENTACIONES, CONSULTAS O
RECLAMOS QUE SE LES PRESENTEN DIRECTAMENTE POR EL CONTRATANTE, ASEGURADO, BENEFICIARIOS O LEGÍTIMOS
INTERESADOS O SUS MANDATARIOS.<br>
LAS PRESENTACIONES PUEDEN SER EFECTUADAS EN TODAS LAS OFICINAS DE LAS ENTIDADES QUE SE ATIENDA PÚBLICO,
PRESENCIALMENTE, POR CORREO POSTAL, MEDIOS ELECTRÓNICOS, O TELEFÓNICAMENTE, SIN FORMALIDADES, EN EL HORARIO
NORMAL DE ATENCIÓN.<br>
RECIBIDA UNA PRESENTACIÓN, CONSULTA O RECLAMO, ÉSA DEBERÁ SER RESPONDIDA EN EL PLAZO MÁS BREVE POSIBLE, EL QUE
NO PODRÁ EXCEDER DE 20 DIÁS HÁBILES CONTADOS DESDE SU RECEPCIÓN.<br>
INTERESADO, EN CASO DE DISCONFORMIDAD RESPECTO DE LO INFORMADO, O BIEN CUANDO EXISTA DEMORA INJUSTIFICADA DE LA
RESPUESTA, PODRÁ RECURRIR A LA COMISIÓN PARA EL MERCADO FINANCIERO, ÁREA DE PROTECCIÓN AL INVERSIONISTA Y
ASEGURADO, CUYAS OFICINAS SE ENCUENTRAN UBICADAS EN AVDA. LIBERTADOR BERNARDO O'HIGGINS 1449 PISO 1, SANTIAGO, O
A TRAVÉS DEL SITIO WEB WWW.CMFCHILE.CL.
</span>
<div class="first" style="text-align: center">TABLA DE DIVERSIFICACIÓN DE PRODUCCIÓN</div>
<span class="gris" style="text-align: justify;">
	<br>
	INFÓRMESE EN LA COMISIÓN PARA EL MERCADO FINANCIERO SOBRE LA GARANTÍA MEDIANTE BOLETA BANCARIA O PÓLIZA QUE,
CONFORME A LA LEY, DEBEN CONSTITUIR LOS CORREDORES DE SEGUROS.<br>
LA INFORMACIÓN SOBRE LA DIVERSIFICACIÓN DE LOS NEGOCIOS DE ESTA CORREDORA Y DE LAS ENTIDADES ASEGURADORAS CON
QUE HAYA TRABAJADO, ASÍ COMO LA INFORMACIÓN DE LAS PÓLIZAS DE SEGUROS CONTRATADAS PARA RESPONDER DEL
CUMPLIMIENTO DE SUS OBLIGACIONES COMO INTERMEDIARIA Y EN CUMPLIMIENTO A LA LEY Y A LAS INSTRUCCIONES IMPARTIDAS
POR LA COMISIÓN PARA EL MERCADO FINANCIERO, INFORMAMOS QUE DURANTE EL AÑO CALENDARIO ANTERIOR INTERMEDIAMOS
CONTRATOS DE SEGUROS CON LAS COMPAÑÍAS QUE SE INDICAN EN LA FECU 2017 DE ARTHUR J. GALLAGHER CORREDORES DE
SEGUROS S.A. (ART. 57 DFL 251) SON LAS SIGUIENTES:<br>
</span>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<table border="1" cellpadding="2" class="tablegreen">
	<tr>
			<td><span class="negrita"> COMPAÑÍAS SEGUROS DE VIDA</span></td>
			<td style="text-align: center"><span class="negrita">%</span></td>
			<td> <span class="negrita">COMPAÑÍAS SEGUROS GENERALES </span></td>
			<td style="text-align: center"><span class="negrita">%</span></td>
	</tr>
	<tr>
		<td>BCI SEGUROS VIDA S.A</td>
		<td style="text-align: center">21,7%</td>
		<td>ACE</td>
		<td style="text-align: center">77,8%</td>
	</tr>
	<tr>
		<td>ACE / CHUBB</td>
		<td style="text-align: center">19,8%</td>
		<td>MAPFRE COMPAÑÍA DE SEGUROS GENERALES
DE CHILE S.A.
</td>
		<td style="text-align: center">4,3%</td>
	</tr>
	<tr>
		<td>CHILENA CONSOLIDADA SEGUROS DE VIDA S.A.</td>
		<td style="text-align: center">15,3%</td>
		<td>SEGUROS GENERALES SURAMERICANA S.A.</td>
		<td style="text-align: center">3,7%</td>
	</tr>
	<tr>
		<td>OHIO NATIONAL SEGUROS DE VIDA S.A</td>
		<td style="text-align: center">10,5% </td>
		<td>HDI SEGUROS S.A.</td>
		<td style="text-align: center">3,3%</td>
	</tr>
	<tr>
		<td>COLMENA COMPAÑÍA DE SEGUROS DE VIDA S.A</td>
		<td style="text-align: center">8,5%</td>
		<td>BCI SEGUROS GENERALES S.A.</td>
		<td style="text-align: center">3,0%</td>
	</tr>
	<tr>
		<td>EUROAMERICA SEGUROS DE VIDA S.A.</td>
		<td style="text-align: center">6,4%</td>
		<td>ORION SEGUROS GENERALES S.A.</td>
		<td style="text-align: center">2,8%</td>
	</tr>
	<tr>
		<td>BICE VIDA COMPAÑÍA DE SEGUROS S.A.</td>
		<td style="text-align: center">5,7%</td>
		<td>LIBERTY COMPAÑÍA DE SEGUROS GENERALES
S.A.</td>
		<td style="text-align: center">2,1%</td>
	</tr>
	<tr>
		<td>COMPAÑÍA DE SEGUROS VIDA CÁMARA S.A.</td>
		<td style="text-align: center">4,1%</td>
		<td>AIG</td>
		<td style="text-align: center">2,1%</td>
	</tr>
	<tr>
		<td>SEGUROS VIDA SECURITY PREVISIÓN S.A. </td>
		<td style="text-align: center">2,8%</td>
		<td>CHILENA CONSOLIDADA SEGUROS GENERALES
S.A.</td>
		<td style="text-align: center">0,4%</td>
	</tr>
	<tr>
		<td>METLIFE CHILE SEGUROS DE VIDA S.A.</td>
		<td style="text-align: center">1,7%</td>
		<td>REALE CHILE SEGUROS GENERALES S.A</td>
		<td style="text-align: center">0,3%</td>
	</tr>
	<tr>
		<td>HDI SEGUROS VIDA S.A.</td>
		<td style="text-align: center">1,4%</td>
		<td>CHUBB</td>
		<td style="text-align: center">0,2%</td>
	</tr>
	<tr>
		<td>COMPAÑÍA DE SEGUROS DE VIDA CONSORCIO
NACIONAL DE SEGUROS
</td>
		<td style="text-align: center">1,4%</td>
		<td></td>
		<td style="text-align: center"></td>
	</tr>
	<tr>
		<td>MAPFRE COMPAÑÍA DE SEGUROS DE VIDA DE
CHILE S.A.
</td>
		<td style="text-align: center">0,5%</td>
		<td></td>
		<td style="text-align: center"></td>
	</tr>
	<tr>
		<td><span class="negrita">TOTAL</span></td>
		<td style="text-align: center"><span class="negrita">100%</span></td>
		<td><span class="negrita">TOTAL</span></td>
		<td style="text-align: center"><span class="negrita">100%</span></td>
	</tr>
</table>
<br>
<div class="first" style="text-align: center">ANEXO N°1</div>
<br>
<span class="negrita" style="text-align: center">INFORMACIÓN DE LAS COMISIONES CIRCULAR N° 2123<br>
(COMISIÓN PARA EL MERCADO FINANCIERO)
</span>
<br>
<span class="gris" style="text-align: justify;">DE ACUERDO A LO INSTRUIDO EN LA CIRCULAR N° 2123 DE FECHA DE 22 DE OCTUBRE DE 2013 DE LA COMISIÓN PARA EL MERCADO
FINANCIERO (CMF), LE INFORMAMOS QUE LAS COMISIONES PAGADAS POR BCI SEGUROS VIDA S.A., RESPECTO DE LA PRIMA PAGADA
POR USTED SON LAS SIGUIENTES:</span>
<br>
<table border="1" cellpadding="2" class="tablegreen">
	<tr>
			<td>
				<span class="negrita">COMISIÓN DE INTERMEDIACIÓN</span>
				<br>
				<span class="gris">ARTHUR J. GALLAGHER CORREDORES<br>DE SEGUROS S.A.<br>RUT: 77.682.370-8<br>COMISIÓN: 5% + IVA SOBRE LA<br>PRIMA NETA RECAUDADA.</span>

			</td>
			<td>
				<span class="negrita">COMISIÓN DE RECAUDACIÓN</span>
				<br>
				<span class="gris">SOLVENTA TARJETAS S.A.<br>RUT: 96.776.000-5<br>COMISIÓN: 57,45% (EXENTA DE IVA), SOBRE LA<br>PRIMA NETA RECAUDADA.</span>

			</td>
			<td>
				<span class="negrita">COMISIÓN USO DE CANAL</span>
				<br>
				<span class="gris">SOLVENTA TARJETAS S.A.<br>RUT: 96.776.000-5<br>COMISIÓN: 17,55% + IVA, SOBRE LA<br>PRIMA NETA RECAUDADA.</span>


			</td>
	</tr>
</table>
<br>
<div class="first" style="text-align: center">ANEXO N°2</div>
<br>
<span class="negrita" style="text-align: center;">(CIRCULAR N° 2106 COMISIÓN PARA EL MERCADO FINANCIERO)<br>
PROCEDIMIENTO DE LIQUIDACIÓN DE SINIESTROS</span>
<br>
<span class="gris" style="text-align: justify;">
	<span class="negrita">1) OBJETO DE LA LIQUIDACIÓN</span>
	LA LIQUIDACIÓN TIENE POR FIN ESTABLECER LA OCURRENCIA DE UN SINIESTRO, DETERMINAR SI EL SINIESTRO ESTÁ CUBIERTO EN
LA PÓLIZA CONTRATADA EN UNA COMPAÑÍA DE SEGUROS DETERMINADA, Y CUANTIFICAR EL MONTO DE LA PÉRDIDA Y DE LA
INDEMNIZACIÓN A PAGAR.<br>
EL PROCEDIMIENTO DE LIQUIDACIÓN ESTÁ SOMETIDO A LOS PRINCIPIOS DE CELERIDAD Y ECONOMÍA PROCEDIMENTAL, DE
OBJETIVIDAD Y CARÁCTER TÉCNICO Y DE TRANSPARENCIA Y ACCESO
</span>

<br>
<span class="gris" style="text-align: justify;">
	<span class="negrita">2) FORMA DE EFECTUAR LA LIQUIDACIÓN
</span>
	LA LIQUIDACIÓN PUEDE EFECTUARLA DIRECTAMENTE LA COMPAÑÍA O ENCOMENDARLA A UN LIQUIDADOR DE SEGUROS. LA DECISIÓN
DEBE COMUNICARSE AL ASEGURADO DENTRO DEL PLAZO DE TRES DÍAS HÁBILES CONTADOS DESDE LA FECHA DE LA DENUNCIA
DEL SINIESTRO.
</span>

<br>
<span class="gris" style="text-align: justify;">
	<span class="negrita">3) DERECHO DE OPOSICIÓN A LA LIQUIDACIÓN DIRECTA

</span>
	EN CASO DE LIQUIDACIÓN DIRECTA POR LA COMPAÑÍA, EL ASEGURADO O BENEFICIARIO PUEDE OPONERSE A ELLA, SOLICITÁNDOLE
POR ESCRITO QUE DESIGNE UN LIQUIDADOR DE SEGUROS, DENTRO DEL PLAZO DE CINCO DÍAS HÁBILES CONTADOS DESDE LA
NOTIFICACIÓN DE LA COMUNICACIÓN DE LA COMPAÑÍA. LA COMPAÑÍA DEBERÁ DESIGNAR AL LIQUIDADOR EN EL PLAZO DE DOS DÍAS
HÁBILES CONTADOS DESDE DICHA OPOSICIÓN.
</span>
<br>
<span class="gris" style="text-align: justify;">
	<span class="negrita">4) INFORMACIÓN AL ASEGURADO DE GESTIONES A REALIZAR Y PETICION DE ANTECEDENTES

</span>
	EL LIQUIDADOR O LA COMPAÑÍA DEBERÁ INFORMAR AL ASEGURADO, POR ESCRITO, EN FORMA SUFICIENTE Y OPORTUNA, AL
CORREO ELECTRÓNICO (INFORMADO EN LA DENUNCIA DEL SINIESTRO) O POR CARTA CERTIFICADA (AL DOMICILIO SEÑALADO EN LA
DENUNCIA DE SINIESTRO), DE LAS GESTIONES QUE LE CORRESPONDE REALIZAR, SOLICITANDO DE UNA SOLA VEZ, CUANDO LAS
CIRCUNSTANCIAS LO PERMITAN, TODOS LOS ANTECEDENTES QUE REQUIERE PARA LIQUIDAR EL SINIESTRO.
</span>

<br>
<span class="gris" style="text-align: justify;">
	<span class="negrita">5) PRE-INFORME DE LIQUIDACIÓN</span>
	EN AQUELLOS SINIESTROS EN QUE SURGIEREN PROBLEMAS Y DIFERENCIAS DE CRITERIOS SOBRE SUS CAUSAS, EVALUACIÓN DEL
RIESGO O EXTENSIÓN DE LA COBERTURA, PODRÁ EL LIQUIDADOR, ACTUANDO DE OFICIO O A PETICIÓN DEL ASEGURADO, EMITIR UN
PRE-INFORME DE LIQUIDACIÓN SOBRE LA COBERTURA DEL SINIESTRO Y EL MONTO DE LOS DAÑOS PRODUCIDOS, EL QUE DEBERÁ
PONERSE EN CONOCIMIENTO DE LOS INTERESADOS. EL ASEGURADO O LA COMPAÑÍA PODRÁN HACER OBSERVACIONES POR ESCRITO
AL PRE-INFORME DENTRO DEL PLAZO DE CINCO DÍAS HÁBILES DESDE SU CONOCIMIENTO.
</span>

<br>
<br>
<br>
<span class="gris" style="text-align: justify;">
	<span class="negrita">6) PLAZO DE LIQUIDACIÓN</span>
	DENTRO DEL MÁS BREVE PLAZO, NO PUDIENDO EXCEDER DE 45 DÍAS CORRIDOS DESDE FECHA DENUNCIO, A EXCEPCIÓN DE;<br>
A) SINIESTROS QUE CORRESPONDAN A SEGUROS INDIVIDUALES SOBRE RIESGOS DEL PRIMER GRUPO CUYA PRIMA ANUAL SEA
SUPERIOR A 100 UF: 90 DÍASCORRIDOS DESDE FECHA DENUNCIO;<br>
B) SINIESTROS MARÍTIMOS QUE AFECTEN A LOS CASCOS O EN CASO DE AVERÍA GRUESA: 180 DÍAS CORRIDOS DESDE FECHA
DENUNCIO.
</span>

<br>
<span class="gris" style="text-align: justify;">
	<span class="negrita">7) PRORROGA DEL PLAZO DE LIQUIDACIÓN</span>
	LOS PLAZOS ANTES SEÑALADOS PODRÁN, EXCEPCIONALMENTE SIEMPRE QUE LAS CIRCUNSTANCIAS LO AMERITEN, PRORROGARSE,
SUCESIVAMENTE POR IGUALES PERÍODOS, INFORMANDO LOS MOTIVOS QUE LA FUNDAMENTEN E INDICANDO LAS GESTIONES
CONCRETAS Y ESPECÍFICAS QUE SE REALIZARÁN, LO QUE DEBERÁ COMUNICARSE AL ASEGURADO Y A LA COMISIÓN PARA EL
MERCADO FINANCIERO, PUDIENDO ESTA ÚLTIMA DEJAR SIN EFECTO LA AMPLIACIÓN, EN CASOS CALIFICADOS, Y FIJAR UN PLAZO
PARA ENTREGA DEL INFORME DE LIQUIDACIÓN. NO PODRÁ SER MOTIVO DE PRÓRROGA LA SOLICITUD DE NUEVOS ANTECEDENTES
CUYO REQUERIMIENTO PUDO PREVERSE CON ANTERIORIDAD, SALVO QUE SE INDIQUEN LAS RAZONES QUE JUSTIFIQUEN LA FALTA DE
REQUERIMIENTO, NI PODODRÁN PRORROGARSE LOS SINIESTROS EN QUE NO HAYA EXISTIDO GESTIÓN ALGUNA DEL LIQUIDADOR,
REGISTRADO O DIRECTO.
</span>
<br>
<span class="gris" style="text-align: justify;">
	<span class="negrita">8) INFORME FINAL DE LIQUIDACIÓN</span>
	EL INFORME FINAL DE LIQUIDACIÓN DEBERÁ REMITIRSE AL ASEGURADO Y SIMULTÁNEAMENTE AL ASEGURADOR, CUANDO
CORRESPONDA, Y DEBERÁ CONTENER NECESARIAMENTE LA TRANSCRIPCIÓN ÍNTEGRA DE LOS ARTÍCULOS 26 Y 27 DEL
REGLAMENTO DE AUXILIARES DEL COMERCIO DE SEGUROS (D.S. DE HACIENDA N° 1.055, DE 2012, DIARIO OFICIAL DE 29 DE
DICIEMBRE DE 2012).

</span>
<br>
<span class="gris" style="text-align: justify;">
	<span class="negrita">9) IMPUGNACION INFORME DE LIQUIDACIÓN</span>
	RECIBIDO EL INFORME DE LIQUIDACIÓN, LA COMPAÑÍA Y EL ASEGURADO DISPONDRÁN DE UN PLAZO DE DIEZ DÍAS HÁBILES PARA
IMPUGNARLA. EN CASO DE LIQUIDACIÓN DIRECTA POR LA COMPAÑÍA, ESTE DERECHO SÓLO LO TENDRÁ EL ASEGURADO.
IMPUGNADO EL INFORME, EL LIQUIDADOR O LA COMPAÑÍA DISPONDRÁ DE UN PLAZO DE 6 DÍAS HÁBILES PARA RESPONDER LA
IMPUGNACIÓN.
</span>
